<?php $module = 'file'; ?>

<!-- Begin Module -->
<div class="cm decorated padded m_<?= $module ?> m-<?= $this->internal->target->currentModule->module_id ?>-<?= $this->internal->target->currentModule->counter ?>">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>

                    <td class="mn1"><h1><a href="<?=(
                    !(isset($this->internal->params->nomid) && $this->internal->params->nomid)
                    ?
                    '/' . $this->SEO_Urlify($this->internal->target->currentModule->display ? $this->internal->target->currentModule->display : $this->internal->target->currentModule->m_display) . '/s' . (isset($this->internal->target->pre) ? $this->internal->target->pre : '') . '/' . $this->internal->target->currentModule->m_name . '/p/mid/' . $this->internal->params->mid . '/'
                    :
                    '/' . $this->SEO_Urlify($this->internal->target->currentModule->display ? $this->internal->target->currentModule->display : $this->internal->target->currentModule->m_display) . '/s' . (isset($this->internal->target->pre) ? $this->internal->target->pre : '') . '/' . $this->internal->target->currentModule->m_name . '/p/nomid/1/'
                    )?>
                    "><?= $this->escape(isset($this->internal->target->currentModule->display) && $this->internal->target->currentModule->display ? $this->internal->target->currentModule->display : $this->internal->target->currentModule->m_display) ?></a></h1></td>
                    <td class="sep"></td>
                    <td class="mn2"><?php if (!$this->masked && !(isset($this->internal->params->nomid) && $this->internal->params->nomid)&& ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_WRITE)) { ?>
<div class="administer"><a href="<?= $this->internal->target->pre ?>/<?= $module ?>/create/p/mid/<?= $this->internal->params->mid ?>/" class="create">Upload New File</a></div>
<?php } ?></td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="bd">
<?php
if ($this->internal->target->currentModule->content) {
    echo '<div class="index_content">' . $this->internal->target->currentModule->content . '</div>';
}
?>

<?php
$counter = 0;

foreach ($this->paginator as $object) {
    $counter++;
    if ($this->internal->target->acl->owner ||
        (!isset($object->allowed) || $object->allowed === null) ||
        $object->show_on_fail ||
        ($object->allowed && ($object->privilege >= ViaMe_Controller_Action::ACL_READ)) ||
        ($this->internal->target->acl->recursive && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_READ))) {
            
        // Create the link
        /*
        $link = '/' . $this->SEO_Urlify($object->title) . '/s';
        if ($this->masked) {
            $link .= $this->internal->target->pre . "/$module/view/p/mid/" . $this->masked . '/id/' . $object->counter . '/';
        }
        else {
            if ($object->com_id && ((isset($this->internal->params->com_id) && $this->internal->params->com_id) || $object->com_id != $this->internal->community->id)) { $link .= '/com/' . $object->com_id; }
            elseif ($object->net_id) { $link .= '/net/' . $object->net_id; }
            elseif ($object->via_id) { $link .= '/via/' . $object->via_id; }
            
            $link .= "/$module/view/p/mid/" . $object->matrix_counter . '/id/' . $object->counter . '/';
        }
        */
        $link = $this->ContentLink(array('object' => $object, 'view' => $this));
        
        // Access link - Sync with View Controller
        $access_link = (
            $object->public_location ? 
                ($this->internal->config->upload->public_server . ($object->title ? '/' . $this->escape($this->SEO_Urlify($object->title)) : '/No-Title') . '/' . $object->file_dir . '/' . $object->file_id . '/' . urlencode($object->file_name))
                :
                (($object->title ? '/' . $this->escape($this->SEO_Urlify($object->title)) . '/s' : '') . $this->internal->target->pre . '/file/view/check/mid/' . (isset($this->masked) ? $this->masked : $object->matrix_counter) . '/id/' . $object->counter . '/file/' . $object->file_id . '/' . urlencode($object->file_name))
        );
?>

<div class="<?= $module ?> <?= ($counter % 2) ? 'odd' : 'even' ?><?= ($counter == 1) ? ' firstitem' : (($counter == count($this->objects)) ? ' lastitem' : '') ?><?= ($object->active == false ? ' draftitem' : '') ?><?= ($object->published_display_activated == false ? ' futureitem' : '') ?><?= ($object->published_display_expired == true ? ' expireditem' : '') ?>">

    <h2 class="title"><a href="<?= $link ?>"><?= $this->escape($object->title) ?></a><?= ($object->active == false ? ' <span class="drafttype">(Draft)</span>' : '') ?><?= ($object->published_display_activated == false ? ' <span class="futuretype">(Future)</span>' : '') ?><?= ($object->published_display_expired == true ? ' <span class="expiredtype">(Expired)</span>' : '') ?></h2>
    
    <div class="part1">
        <div class="author">Uploaded By <?= $this->ProfileDisplay(array('profile' => $object, 'internal' => $this->internal)) ?></div>
        
        <div class="datetime">Uploaded: 
        <?php
            $date = new Zend_Date();
            $date->set($object->published_display_date, Zend_Date::ISO_8601);
            if (isset($this->internal->member)) {
                $date->setTimezone($this->internal->member->timezone);
                echo $date->toString(Zend_Date::DATE_FULL . ' ' . Zend_Date::TIME_SHORT);
            }
            else {
                $date->setTimezone($this->internal->config->timezone);
                echo $date->toString(Zend_Date::DATE_FULL . ' ' . Zend_Date::TIME_SHORT . ' z');
            }
        ?>
        </div>
        
        <div class="relay">
            <?= $this->PrintEmailLink(array('link' => $link, 'internal' => $this->internal)) ?>
        </div>
    </div>

    <div class="part2">
        <div class="summary">
            <table class="fileinfo">
                <tr>
                    <td rowspan="3" style="width: 1px;">
                        <a href="<?= ($access_link ? $access_link : $link) ?>"><img src="http://www.stdicon.com/crystal/<?= ($object->file_name ? $object->file_name : $object->file_type) ?>?size=50&default=http%3A%2F%2Fwww.stdicon.com%2Fcrystal%2Fapplication%2Foctet-stream%3Fsize%3D50" /></a>
                    </td>
                    <td class="item">FileName:</td>
                    <td class="value"><a href="<?= ($access_link ? $access_link : $link) ?>"><?= $object->file_name ?></a></td>
                </tr>
                <tr>
                    <td class="item">FileSize:</td>
                    <td class="value">
<?php

$size = $object->file_size;
$ext = 'Byte';

if ($size >= (1024 * 1024 * 1024)) {
    $size = $size / 1024 / 1024 / 1024;
    $ext = 'GB';
}
elseif ($size >= (1024 * 1024)) {
    $size = $size / 1024 / 1024;
    $ext = 'MB';
}
elseif ($size >= 1024) {
    $size = $size / 1024;
    $ext = 'KB';
}

echo Zend_Locale_Format::toNumber($size, array('precision' => 2)) . " $ext" . ($size > 1 ? 's' : '');
?>
                    </td>
                </tr>
                <tr>
                    <td class="item">MimeType:</td>
                    <td class="value"><?= $object->file_type ?></td>
                </tr>
            </table>

<?php /*if ($object->description) { ?>            
<p style="margin-top: 1em;"><?= $this->escape($object->description) ?></p>
<?php } */?>
        </div>
    </div>

    <div class="part3">
        <?php if ($this->internal->target->currentModule->interactive && ($this->masked ? $object->x_interactive : true)) { ?>
            <div class="interact">
                <div class="comments"><span class="begin_comment_count">&nbsp;</span><a href="<?= $link ?>#comments_list" class="comment_count"><?= $object->total_comments_count ?></a><span class="end_comment_count">&nbsp;</span> <a href="<?= $link ?>#comments_list">Comment(s)</a></div>
                <div class="rating">Rating <span class="count rc<?= floor($object->rating * 2) ?>"><?= ($object->rating ? $object->rating : 'N/A') ?></span></div>
            </div>
        <?php } ?>
    </div>

</div>

<?php
    }
}
?>


<?php echo $this->paginationControl($this->paginator, 'Sliding', 'index/paginator.phtml', array('internal' => $this->internal)); ?>


    </div>
    
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>

        </div>
    </div>
    <span class="icon"></span>
</div>
<!-- End Module -->






<?php /*

<h1><?= $this->escape(isset($this->internal->target->currentModule->display) && $this->internal->target->currentModule->display ? $this->internal->target->currentModule->display : $this->internal->target->currentModule->m_display) ?></h1>

<?php if (!$this->masked && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_WRITE)) { ?>
<p><a href="<?= $this->internal->target->pre ?>/file/create/p/mid/<?= $this->internal->params->mid ?>/">Upload New File</a></p>
<?php } ?>

<?php
foreach ($this->paginator as $file) {
    if ($this->internal->target->acl->owner ||
        $file->allowed === null ||
        $file->show_on_fail ||
        ($file->allowed && ($file->privilege >= ViaMe_Controller_Action::ACL_READ)) ||
        ($this->internal->target->acl->recursive && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_READ))) {
        
        // Create the link
        $link = '/' . $this->escape($this->SEO_Urlify($file->title ? $file->title : $file->file_name)) . '/s';
        if ($this->masked) {
            $link .= $this->internal->target->pre . '/file/view/p/mid/' . $this->masked . '/id/' . $file->counter . '/';
        }
        else {
            if ($file->com_id && ((isset($this->internal->params->com_id) && $this->internal->params->com_id) || $file->com_id != $this->internal->community->id)) { $link .= '/com/' . $file->com_id; }
            elseif ($file->net_id) { $link .= '/net/' . $file->net_id; }
            elseif ($file->via_id) { $link .= '/via/' . $file->via_id; }
            
            $link .= '/file/view/p/mid/' . $file->matrix_counter . '/id/' . $file->counter . '/';
        }
?>

<h2><a href="<?= $link ?>"><?= $this->escape(($file->title ? $file->title : $file->file_name)) ?></a></h2>

<blockquote>
<?php if ($this->internal->target->currentModule->interactive && ($this->masked ? $this->file->x_interactive : true)) { ?>
    <p class="interact"><a href="<?= $link ?>#comments_list"><?= $file->total_comments_count ?> Comment(s)</a> - Average Rating : <?= ($file->rating ? $file->rating : 'N/A') ?></p>
<?php } ?>
    <p class="datetime">
<?php
    $date = new Zend_Date();
    $date->set($file->creation, Zend_Date::ISO_8601);
    if (isset($this->internal->member)) {
        $date->setTimezone($this->internal->member->timezone);
    }
    echo $date->toString('EEEE  MMMM d, YYY h:mm a z');
?>
    </p>
    
    <p>By <?= $this->ProfileDisplay(array('profile' => $file, 'internal' => $this->internal)) ?></p>
    
    <p><?= $this->escape($file->description) ?></p>
</blockquote>

<?php
    }
}
?>




<?php echo $this->paginationControl($this->paginator, 'Sliding', 'index/paginator.phtml', array('internal' => $this->internal)); ?>

*/ ?>
