<p>Your <strong>unsubscribe request</strong> from <strong><?= $this->subscription->title ?></strong> has been successfully processed.</p>

<p><strong>Your access will continue to be active up through the paid period and you will not be re-billed.</strong></p>

<p>If you should have any problems or would like to leave us a comment, please contact our customer service team by sending an email to <a href="mailto:<?= $this->internal->community->email ?>"><?= $this->internal->community->email ?></a>.</p>

<p>Sincerely,</p>

<p><strong><?= $this->internal->community->display ?></strong></p>