<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Sign-Up Now...Free!
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem selected"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>


 						
<!-- Begin Module -->
<div class="cm decorated">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">SmallCap Network Elite Opportunity Free Alerts!</td>
                    <td class="sep"></td>
                    <td class="mn2">Welcome<?= $this->fnwelcome ? ', ' . $this->escape($this->fnwelcome) : '' ?>!</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd padded">

<?php /*
<p class="welcome">
    Hi<?= $this->fnwelcome ? ', ' . $this->escape($this->fnwelcome) : '' ?>!
    We just need a little <?= ($_SERVER['QUERY_STRING'] || count($_POST)) ? 'more' : '' ?> information for you to join the <?= $this->internal->community->display ?> community.
</p>
*/ ?>

<?php
if ($this->formErrors) {
    print '<ul class="errors" style="margin-bottom: 1em;">';
    foreach ($this->formErrors as $message) {
        print "<li>$message</li>\n";
    }
    print '</ul>';
}
?>

<?= $this->form ?>


    </div>
    <div class="ft">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
    </div>
    
    <span class="icon"></span>
</div>
<!-- End Module -->


<?= $this->FormHelper(array('internal' => $this->internal)) ?>