<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Confirmed
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem selected"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>

<!-- Begin Module -->
<div class="cm decorated plain successmessage">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Setup Alerts</td>
                    <td class="sep"></td>
                    <td class="mn2">Receive Free Alerts Via Text Message</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd">
        <p class="success">Your email address has been confirmed.</p>
        <p><strong>You're almost finished!</strong>  Avoid delays now by receiving our free mobile text alerts, which are far quicker and more timely than email.  <strong>Individuals who provide their mobile phone numbers will be the first to receive our alerts.</strong></p>
        <p><strong>Please provide your mobile phone number below.</strong> Make sure to include your country code, area code and phone number. Once you have finished, hit the <strong>"Sign-Up For Mobile Alerts"</strong> button and a confirmation code will be sent via text directly to your mobile phone. Simply enter the confirmation code on the next page and you will be all dialed in to start receiving the <strong>SmallCap Network Elite Opportunity Free Mobile Text and Email Alerts</strong>.</p>

<div style="width:400px; margin: 0 auto;">
<form id="alert_form" name="alert_form" enctype="application/x-www-form-urlencoded" method="POST" action="/member/scneol/mobile/" class="form" onSubmit="return (YAHOO.viame.vivin_regula.validate(this, { groups: [regula.Group.alert_form] }) && YAHOO.viame.dubsub.check(this));">
<input type="hidden" name="vmpd_bpip" value="1" id="vmpd_bpip" />
<input type="hidden" name="vmpd_npr" value="1" id="vmpd_npr" />
<input type="hidden" name="id" value="<?= $this->member->id ?>" id="id" />
<input type="hidden" name="email" value="<?= $this->member->email ?>" id="email" />
  <dl class="zend_form">
    <dt id="main-label">&#160;</dt>
    <dd id="main-element">
      <fieldset id="fieldset-main">
        <dl>
          <dt id="mobile-label">
            <label for="mobile" class="required">Mobile # : <span class="netdown">US Numbers Should Start With "1"</span></label>
          </dt>
          <dd id="mobile-element">
            <input type="text" name="mobile" id="mobile" value="" maxlength="256" class="regula-validation" data-constraints="@Required(label=&quot;mobile #&quot;, message=&quot;The {label} field cannot be empty.&quot;, groups=[alert_form])" />
            <p class="description">Enter your phone number, <strong class="netdown">including full country code and area code</strong> for instant text alerts (i.e., 16195551212 for U.S. domestic users; International users should not include 011 or 00)</p>
          </dd>
        </dl>
      </fieldset>
    </dd>
    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <dt id="submit-label">&#160;</dt>
          <dd id="submit-element">
            <input type="submit" name="submit" id="submit" value="Sign-Up For Mobile Alerts" />
          </dd>
        </dl>
      </fieldset>
    </dd>
    <dt id="hidden-label">&#160;</dt>
    <dd id="hidden-element">
      <fieldset id="fieldset-hidden">
        <dl>
          <dt id="vmpd_nar-label">&#160;</dt>
          <dd id="vmpd_nar-element">
            <input type="hidden" name="vmpd_nar" value="1" id="vmpd_nar" />
          </dd>
          <dt id="redirect-label">&#160;</dt>
          <dd id="redirect-element">
            <input type="hidden" name="redirect" value="" id="redirect" />
          </dd>
        </dl>
      </fieldset>
    </dd>
  </dl>
</form>
</div>




    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
    <span class="icon"></span>
</div>
<!-- End Module -->




<?php $this->headScript()->captureStart(); ?>

window.dataLayer = window.dataLayer || [];
dataLayer.push({
    'adwordsConversion_id': '1071423029',
    'adwordsConversion_label': '9PFgCIPgv1kQtbzy_gM'
});

<?php $this->headScript()->captureEnd(); ?>


<?php /* MOVED TO GTM
<!-- Google Code for SCNEO Free Alerts - Email Confirmed Conversion Page -->
<script type="text/javascript">
var google_conversion_id = 1071423029;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "9PFgCIPgv1kQtbzy_gM";
var google_remarketing_only = false;
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1071423029/?label=9PFgCIPgv1kQtbzy_gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
*/ ?>