<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link href="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/stylesheet.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?= $this->internal->vars->static_host ?>/css/theme/default/stylesheet.css" media="screen" rel="stylesheet" type="text/css" title="Default" />
<style type="text/css" media="screen">
<!--
body { padding: 1em; }
-->
</style>
</head>

<body>

<center>
<!--Start Email-->
<table border="0" cellspacing="0" cellpadding="18" align="center" class="email" style="font-family: Arial, Helvetica, sans-serif; font-size: 13px; width: 560px; color: #333;">
    <tr>
        <td class="header" style="padding: 18px; background-color: #121e46; border-top-left-radius: 10px; border-top-right-radius: 10px; -moz-border-radius-topleft: 10px; -moz-border-radius-topright: 10px; -webkit-border-top-left-radius: 10px; -webkit-border-top-right-radius: 10px;"><a href="https://www.smallcapnetwork.com" title="SmallCap Network"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/logo/logo.png" border="0" alt="SmallCap Network Logo" /></a></td>
    </tr>
    <tr>
        <td class="subject" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; background-color: #e8eef0; color: #213d70; font-size: 16px; font-weight: bold;"><?= $this->layout()->subject ?></td>
    </tr>
    <tr>
        <td class="bd" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; background: #fff url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/page_body_bg.gif) repeat-x 0 -1px;">

<?= $this->layout()->content ?>
        
        </td>
    </tr>
    <tr>
        <td class="footer" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; background-color: #fff; text-align: center; font-size: 11px; color: #808080; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; -moz-border-radius-bottomleft: 10px; -moz-border-radius-bottomright: 10px; -webkit-border-bottom-left-radius: 10px; -webkit-border-bottom-right-radius: 10px;">Copyright &copy; 2001-<?= date('Y') ?> <a href="https://www.smallcapnetwork.com" title="SmallCap Network">SmallCapNetwork.com</a>. All Rights Reserved.</td>
    </tr>
</table>
<!--End Email-->
</center>

</body>
</html>