<div id="content_area">

    <!-- Begin Module -->
    <div class="cm decorated">
        <div class="hd">
            <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
            </div>
            <div class="con">
            	<table class="table">
                    <tr>
                        <td class="lt"></td>
                        <td class="mn1">Sign In to <?= $this->internal->community->display ?></td>
                        <td class="sep"></td>
                        <td class="mn2"></td>
                        <td class="rt"></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="bd padded">
        
    
        <?= $this->render('form.phtml') ?>
    
            
        </div>
        <div class="ft">
            <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
        </div>
        
        <span class="icon"></span>
    </div>
    <!-- End Module -->

</div>