<?php $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js'); ?>
<?php $this->inlineScript()->appendScript("var addthis_share = { templates: { twitter: 'check out {{title}} @ {{url}}' } };\n"); ?>

<?php /*
<script src="https://platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/Share" data-counter="right"></script>
*/ ?>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style">
<a class="addthis_button_facebook_like" fb:like:layout="button_count" rel="nofollow"></a>
<a class="addthis_button_tweet" tw:via="<?= (isset($this->internal->community->name) && $this->internal->community->name != 'default' ? $this->internal->community->name : 'ViaMe') ?>" rel="nofollow"></a>
<div style="display: inline-block; float: left;"><script src="https://platform.linkedin.com/in.js" type="text/javascript"></script><script type="IN/Share" data-counter="right"></script></div>
<a class="addthis_button_google_plusone" g:plusone:size="medium" rel="nofollow"></a>
<a class="addthis_button_pinterest_pinit"></a>
<a class="addthis_counter addthis_pill_style" rel="nofollow"></a>
</div>
<!-- AddThis Button END -->