<?php
/*
 *
 * VM FormHelper
 *
 */

//$this->internal->vars->static_host = '//static.viame.com';
$this->headScript()->appendFile($this->internal->vars->static_host . '/js/vm/yui/viame_form_helper.js');
?>


<?php $this->inlineScript()->captureStart(); ?>
// Some date constants
var vm_date_format_short = '<?=  preg_replace(array('/d+/i', '/m+/i', '/y+/i'), array('dd', 'mm', 'yyyy'), Zend_Locale_Data::getContent($this->internal->locale, 'date', 'short')) ?>';
<?php $this->inlineScript()->captureEnd(); ?>


<?php
// TextArea
if ((isset($_SERVER['HTTP_USER_AGENT']) && preg_match('/(iPhone|iPad)/i', $_SERVER['HTTP_USER_AGENT'])) || (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == -1))) {
    // Plain
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
            YAHOO.util.Dom.setStyle(ta[i], 'height', '30em');
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 7)) {
    // nicEdit
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/nicEdit/nicEdit.js');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
            YAHOO.util.Dom.setStyle(ta[i], 'height', '400px');
            if (!ta[i].value) { ta[i].value = '<p><br /></p>'; }
            new nicEditor({
                iconsPath: '<?= $this->internal->vars->static_host ?>/js/nicEdit/nicEditorIcons.gif',
                maxHeight: 408,
                fullPanel: false,
                buttonList: [ 'fontSize', 'fontFamily', 'fontFormat', 'bold', 'italic', 'underline', 'strikethrough', 'left', 'center', 'right', 'justify', 'ol', 'ul', 'indent', 'outdent', 'hr', 'image', 'link', 'unlink', 'forecolor', 'bgcolor', 'removeformat', 'xhtml' ]
            }).panelInstance(ta[i].id);
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
/* elRTE is gone.  Sucks.  Not supported.  Already removed all of the /js files for it.
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 6)) {
    // elRTE
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/elrte/js/elrte.min.js');
    #$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js');
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/js/elrte/css/elrte.min.css');
    #$this->headLink()->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css');
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/js/elrte/css/adjust.css');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        $(document).ready(function() {
			var opts = {
				height   : 400,
				toolbar  : 'complete',
				cssfiles : ['<?= $this->internal->vars->static_host ?>/js/elrte/css/elrte-inner.css']
			}
			$('.vmfh_textarea').elrte(opts);
		})
    });
    
    <?php $this->inlineScript()->captureEnd();
}
*/
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 5)) {
    // Yahoo! Rich Text Editor
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
            var editor = new YAHOO.widget.Editor(ta[i].id, {
                width: '100%',
                height: '300px',
                animate: false,
                dompath: true,
                focusAtStart: false,
                extracss: 'body { padding: 0; margin: 7px; }',
                handleSubmit: true
            });
            editor.buttonType = 'advanced';
            editor.on('editorContentLoaded', function() {
                resize = new YAHOO.util.Resize(editor.get('element_cont').get('element'), {
                    handles: ['br'],
                    autoRatio: true,
                    status: true,
                    proxy: true,
                    setSize: false //This is where the magic happens
                });
                
                resize.on('startResize', function() {
                    this.hide();
                    this.set('disabled', true);
                }, editor, true);
                resize.on('resize', function(args) {
                    var h = args.height;
                    var th = (this.toolbar.get('element').clientHeight + 2); //It has a 1px border..
                    var dh = (this.dompath.clientHeight + 1); //It has a 1px top border..
                    var newH = (h - th - dh);
                    this.set('width', args.width + 'px');
                    this.set('height', newH + 'px');
                    this.set('disabled', false);
                    this.show();
                }, editor, true);
            });
    	    editor.render();
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 4)) {
    // openWYSIWYG
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/openWYSIWYG/scripts/wysiwyg.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/openWYSIWYG/scripts/wysiwyg-settings.js');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var myWYSIWYGsettings = new WYSIWYG.Settings();
          myWYSIWYGsettings.ImagesDir = "<?= $this->internal->vars->static_host ?>/js/openWYSIWYG/images/";
          myWYSIWYGsettings.PopupsDir = "/js/openWYSIWYG/popups/";
          myWYSIWYGsettings.CSSFile = "<?= $this->internal->vars->static_host ?>/js/openWYSIWYG/styles/wysiwyg.css";
          myWYSIWYGsettings.Width = "99%";
          myWYSIWYGsettings.Height = "400px";
          //myWYSIWYGsettings.InvertIELineBreaks = true;
          myWYSIWYGsettings.PreviewWidth = 800;
          myWYSIWYGsettings.PreviewHeight = 600;
          
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
            if (!ta[i].value) { ta[i].value = '<p>&nbsp;</p>'; }
            WYSIWYG.attach(ta[i].id, myWYSIWYGsettings);
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 3)) {
    // CK Editor
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/ckeditor/ckeditor.js');
    $this->headStyle()->appendStyle("fieldset#fieldset-main #cke_content { width: auto; max-width: 680px; }"); // Webkit Hack
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
        	CKEDITOR.replace(ta[i].id, {
        	    height: "400",
        	    resize_minWidth: "425"
        	});
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 2)) {
    // FCK Editor
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/fckeditor/fckeditor.js');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_textarea');
        for (var i = 0; i < ta.length; i++) {
            var oFCKeditor = new FCKeditor(ta[i].id);
        	oFCKeditor.BasePath	= '/js/fckeditor/';
        	oFCKeditor.Height = 500;
        	oFCKeditor.Config.DocType = '<?= $this->docType() ?>';
        	oFCKeditor.Config.EditorAreaCSS = "<?= $this->internal->vars->static_host ?>/css/community/default/htmleditor.css";
        	oFCKeditor.ReplaceTextarea();
        	
        	// Bug with IE8
        	//var resize = new YAHOO.util.Resize(ta[i].id + '___Frame', {
            //    handles: ['br']
            //}); 
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
elseif (isset($this->internal->member->profile->editor_preference) && ($this->internal->member->profile->editor_preference == 1)) {
    // Tiny MCE
    //  NOTE: If there is an @ sign in the url location, loading of tiny mce plugins is going to cycle and fail on the dynamic backend.
    
    // Had to make nginx mod to allow loading of /js/ from same host/domain
    $this->headScript()->appendFile('/js/tiny_mce/tiny_mce.js');
    
    $this->inlineScript()->captureStart(); ?>
    
    tinyMCE.init({
    	mode : "textareas",
    	convert_urls : false,
    	relative_urls : false,
    	height: 500,
        // Example content CSS (should be your site CSS)
    	content_css : "<?= $this->internal->vars->static_host ?>/css/community/default/htmleditor.css",
    	doctype: '<?= $this->docType() ?>',
    	convert_fonts_to_spans : true,
    	theme : "advanced",
	    //plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager",
    	plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
        editor_selector : "vmfh_textarea",
        
    	// Theme options
    	theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    	theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    	theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
    	theme_advanced_toolbar_location : "top",
    	theme_advanced_toolbar_align : "left",
    	theme_advanced_statusbar_location : "bottom",
    	theme_advanced_resizing : true
    	
    	<?php
    	// If Site Admin, allow more attributes for input elements.
    	if (isset($this->internal->member) && ($this->internal->member->site_admin || $this->internal->member->profile->site_admin)) {
        	echo ',valid_elements : "@[id|class|style|title|dir<ltr?rtl|lang|xml::lang|onclick|ondblclick|"
                + "onmousedown|onmouseup|onmouseover|onmousemove|onmouseout|onkeypress|"
                + "onkeydown|onkeyup],a[rel|rev|charset|hreflang|tabindex|accesskey|type|"
                + "name|href|target|title|class|onfocus|onblur],strong/b,em/i,strike,u,"
                + "#p,-ol[type|compact],-ul[type|compact],-li,br,img[longdesc|usemap|"
                + "src|border|alt=|title|hspace|vspace|width|height|align],-sub,-sup,"
                + "-blockquote,-table[border=0|cellspacing|cellpadding|width|frame|rules|"
                + "height|align|summary|bgcolor|background|bordercolor],-tr[rowspan|width|"
                + "height|align|valign|bgcolor|background|bordercolor],tbody,thead,tfoot,"
                + "#td[colspan|rowspan|width|height|align|valign|bgcolor|background|bordercolor"
                + "|scope],#th[colspan|rowspan|width|height|align|valign|scope],caption,-div,"
                + "-span,-code,-pre,address,-h1,-h2,-h3,-h4,-h5,-h6,hr[size|noshade],-font[face"
                + "|size|color],dd,dl,dt,cite,abbr,acronym,del[datetime|cite],ins[datetime|cite],"
                + "object[classid|width|height|codebase|*],param[name|value|_value],embed[type|width"
                + "|height|src|*],script[src|type],map[name],area[shape|coords|href|alt|target],bdo,"
                + "button,col[align|char|charoff|span|valign|width],colgroup[align|char|charoff|span|"
                + "valign|width],dfn,fieldset,form[action|accept|accept-charset|enctype|method],"
                //+ "input[accept|alt|checked|disabled|maxlength|name|readonly|size|src|type|value],"
                + "input[accept|accesskey|align<bottom?left?middle?right?top|alt|checked<checked|class|dir<ltr?rtl|disabled<disabled|id|ismap<ismap|lang|maxlength|name|onblur|onclick|ondblclick|onfocus|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|onselect|readonly<readonly|size|src|style|tabindex|title|type<button?checkbox?file?hidden?image?password?radio?reset?submit?text|usemap|value],"
                + "kbd,label[for],legend,noscript,optgroup[label|disabled],option[disabled|label|selected|value],"
                + "q[cite],samp,select[disabled|multiple|name|size],small,"
                + "textarea[cols|rows|disabled|name|readonly],tt,var,big"
                
                + "noscript[class|dir<ltr?rtl|id|lang|style|title],"
                + "script[charset|defer|language|src|type]"
                ';
        }
        ?>
    });
    
    <?php $this->inlineScript()->captureEnd();
}
else {
    // Redactor
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/redactor/redactor.min.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/redactor/fullscreen.js');
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/js/redactor/redactor.css');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
    	$(document).ready(
    		function()
    		{
    			$('.vmfh_textarea').redactor({
    			    autoresize: false,
    			    minHeight: 400,
    			    convertDivs: false,
    			    paragraphy: false,
    			    buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', 'underline', 'deleted', '|',
                        'unorderedlist', 'orderedlist', 'outdent', 'indent', '|',
                        'image', 'video', 'file', 'table', 'link', '|',
                        'fontcolor', 'backcolor', '|', 'alignment', '|', 'horizontalrule'],
    			    plugins: ['fullscreen']
    			});
    		}
    	);
    });
    
    <?php $this->inlineScript()->captureEnd();
}
?>



<?php
// TextArea
if ((isset($_SERVER['HTTP_USER_AGENT']) && preg_match('/(iPhone|iPad)/i', $_SERVER['HTTP_USER_AGENT']))) {
    // Plain
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
        var ta = YAHOO.util.Dom.getElementsByClassName('vmfh_codeeditor');
        for (var i = 0; i < ta.length; i++) {
            YAHOO.util.Dom.setStyle(ta[i], 'height', '30em');
        }
    });
    
    <?php $this->inlineScript()->captureEnd();
}
else {
    // CodeMirror
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/lib/codemirror.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/css/css.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/xml/xml.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/clike/clike.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/javascript/javascript.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/htmlmixed/htmlmixed.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/codemirror/mode/php/php.js');
    
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/js/codemirror/lib/codemirror.css');
    
    $this->inlineScript()->captureStart(); ?>
    
    YAHOO.util.Event.onDOMReady(function() {
    	$(document).ready(
    		function()
    		{
    			$('.vmfh_codeeditor').each(function(index) {
    				CodeMirror.fromTextArea(document.getElementById($(this).attr('id')), {
				        mode: $(this).attr('langmode').toLowerCase(),
				        //theme: "",
				        indentUnit: 4,
				        lineWrapping: true,
				        lineNumbers: true,
				        matchBrackets: true
				    });
	            });
	            
	            
    		}
    	);
    });
    
    <?php $this->inlineScript()->captureEnd();
}
?>