<h1><?= isset($this->page_title) && $this->page_title ? $this->page_title : 'Create A New Article' ?></h1>

<form id="article_form" enctype="application/x-www-form-urlencoded" method="post" class="form" action="?" onsubmit="return (YAHOO.viame.vivin_regula.validate(this, { groups: [regula.Group.article_form] }) && YAHOO.viame.dubsub.check(this));"><dl class="zend_form">
<?= $this->form->getDisplayGroup('hidden') ?>

<table style="width: 100%;">
    <tr>
        <td style="width: 230px; min-width: 230px; vertical-align: top;">

<!-- Begin Options -->
<div class="cm decorated options">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">

                <tr>

                    <td class="lt"></td>
                    <td class="mn1">Options</td>
                    <td class="sep"></td>
                    <td class="mn2"></td>
                    <td class="rt"></td>
                </tr>
            </table>

        </div>

    </div>
    <div class="bd">


<!-- Begin Accordion -->
        <div id="options_accordion" class="yui3-accordion">
<?php
    $counter = 0;
    foreach ($this->form->getDisplayGroups() as $group) {
        if (!preg_match('/^options/', $group->getName())) { continue; }
?>
            <div class="yui3-accordion-item yui3-accordion-item-active<?= (!$counter ? ' first-of-type' : '') ?>">
                <div class="yui3-accordion-item-hd">
                    <a href="javascript:void(null);" class="yui3-accordion-item-trigger"><?= $group->getAttrib('legend') ?></a>
                </div>
                <div class="yui3-accordion-item-bd">
                    <p><?php $group->removeAttrib('legend'); echo $group; ?></p>
                </div>
            </div>
<?php
        $counter++;
    }
?>
        </div>
<!-- End Accordion -->


    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
</div>
<!-- End Options -->

        </td>
        <td style="vertical-align: top;"><div style="margin-left: 1em;">

<?php
if ($this->formErrors) {
    print '<div class="errors"><ul>';
    foreach ($this->formErrors as $message) {
        print "<li>$message</li>\n";
    }
    print '</ul></div>';
}

echo $this->form->getDisplayGroup('main');
echo $this->form->getDisplayGroup('buttons');
?>

        </div></td>
    </tr>
</table>
</dl></form>

<?php $this->inlineScript()->captureStart(); ?>
YUI({
    //fetchCSS: false
}).use('anim', 'gallery-node-accordion', function (Y) {
	Y.one("#options_accordion").plug(Y.Plugin.NodeAccordion, {
	    anim: Y.Easing.easeBothStrong
	});	
});
<?php $this->inlineScript()->captureEnd(); ?>

<?= $this->FormHelper(array('internal' => $this->internal)) ?>