<?php
$module = 'message';

/*
if (!$this->masked && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_WRITE)) {
?>
<p class="administer"><a href="<?= $this->internal->target->pre ?>/<?= $module ?>/create/p/mid/<?= $this->widget->counter ?>/">Post A New Message</a></p>
<?php
}
*/

if (isset($this->objects) && $this->objects) {
    $counter = 0;

?>

<table class="display">
    <tr>
        <th scope="col" class="firstitem">Subject</th>
        <th scope="col">Replies</th>
        <th scope="col" class="lastitem">Views</th>
    </tr>


<?php
    foreach ($this->objects as $object) {
        $counter++;
        if ($this->internal->target->acl->owner ||
            $object->allowed === null ||
            $object->show_on_fail ||
            ($object->allowed && ($object->privilege >= ViaMe_Controller_Action::ACL_READ)) ||
            ($this->internal->target->acl->recursive && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_READ))) {
            
            // Create the link
            /*
            $link = 'https://' . $this->internal->vars->host . '/' . $this->SEO_Urlify($object->title) . '/s';
            if ($this->masked) {
                $link .= $this->internal->target->pre . "/$module/view/p/mid/" . $this->masked . '/id/' . $object->counter . '/';
            }
            else {
                if ($object->com_id && ((isset($this->internal->params->com_id) && $this->internal->params->com_id) || $object->com_id != $this->internal->community->id)) { $link .= '/com/' . $object->com_id; }
                elseif ($object->net_id) { $link .= '/net/' . $object->net_id; }
                elseif ($object->via_id) { $link .= '/via/' . $object->via_id; }
                
                $link .= "/$module/view/p/mid/" . $object->matrix_counter . '/id/' . $object->counter . '/';
            }
            */
            $link = $this->ContentLink(array('object' => $object, 'view' => $this));
?>


<tr class="<?= $module ?> <?= ($counter % 2) ? 'odd' : 'even' ?><?= (isset($this->widget->widget_hide_summary) && $this->widget->widget_hide_summary) ? ' hide_summary' : '' ?><?= ($counter == 1) ? ' firstitem' : (($counter == count($this->objects)) ? ' lastitem' : '') ?><?= ($object->active == false ? ' draftitem' : '') ?><?= ($object->published_display_activated == false ? ' futureitem' : '') ?><?= ($object->published_display_expired == true ? ' expireditem' : '') ?>">
    <td class="message_title firstitem">
        <div class="title"><a href="<?= $link ?>"><?= $this->escape($object->title) ?></a><?= ($object->active == false ? ' <span class="drafttype">(Draft)</span>' : '') ?><?= ($object->published_display_activated == false ? ' <span class="futuretype">(Future)</span>' : '') ?><?= ($object->published_display_expired == true ? ' <span class="expiredtype">(Expired)</span>' : '') ?></div>
        <?php if (!(isset($this->widget->widget_hide_summary) && $this->widget->widget_hide_summary)) { ?>
            <div class="summary"><?= ($object->summary ? $this->escape($object->summary) : $this->SEO_Quip($object->content, 40)) ?></div>
        <?php } ?>
        <div>
            <div class="author">By <?= $this->ProfileDisplay(array('profile' => $object, 'internal' => $this->internal)) ?></div>
            <div class="datetime">[
<?php
    $date = new Zend_Date();
    $date->set($object->published_display_date, Zend_Date::ISO_8601);
    
    if ((time() - $date->get(Zend_Date::TIMESTAMP)) < 3600) {
        echo sprintf("%d minute(s) ago", ((time() - $date->get(Zend_Date::TIMESTAMP)) / 60));
    }
    else {
        if (isset($this->internal->member)) {
            $date->setTimezone($this->internal->member->timezone);
            echo $date->toString(Zend_Date::DATE_SHORT . ' ' . Zend_Date::TIME_SHORT);
        }
        else {
            $date->setTimezone($this->internal->config->timezone);
            echo $date->toString(Zend_Date::DATE_SHORT . ' ' . Zend_Date::TIME_SHORT . ' z');
        }
    }
?>
            ]</div>
        </div>

    </td>
    <td class="message_replies"><?= Zend_Locale_Format::toNumber($object->total_replies_count + 0) ?></td>
    <td class="message_views lastitem"><?= Zend_Locale_Format::toNumber($object->total_views_count + 0) ?></td>



</tr>

<?php
        }
    }
?>

</table>

<?php
}
?>