<p><strong>Welcome to the <?= $this->internal->community->display ?> Community!</strong></p>

<p>Please feel free to ask us any questions. We always do our best to get back to you ASAP with an answer. Also, we love feedback, site critique and suggestions, so send them in. We take your comments and suggestions very seriously, so please don't be shy.</p>

<p>Thanks again for becoming a <strong><?= $this->internal->community->display ?> Member</strong>. We look forward to having you as part of our rapidly growing Community.</p>

<p>Sincerely,</p>

<p><strong><?= $this->internal->community->display ?></strong></p>