<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Confirmed
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem selected"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>

<!-- Begin Module -->
<div class="cm decorated plain successmessage">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Welcome</td>
                    <td class="sep"></td>
                    <td class="mn2">SmallCap Network Elite Opportunity Free Alerts Setup Complete</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd">
        
        <p class="success">Congratulations!</p>
        <p>You are all set to start receiving the <strong>SmallCap Network Elite Opportunity Free Mobile Text and Email Alerts</strong>!</p>
        <p>For any questions, comments or feedback, please use the contact us form located at the bottom of our site and make sure to reference our "Free Mobile Text and Email Alerts Service".</p>
        <p>Be on the lookout for your first alert, which should be arriving by mobile text or email, within the next several days.</p>
        <p>Let's make some money together and thank you for becoming a <strong>Free Alerts Member</strong>!</p>
        <p>Sincerely,</p>
        <p><strong>Staff at SmallCap Network Elite Opportunity</strong></p>
        
    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
    <span class="icon"></span>
</div>
<!-- End Module -->




<?php $this->headScript()->captureStart(); ?>

window.dataLayer = window.dataLayer || [];
dataLayer.push({
    'adwordsConversion_id': '1071423029',
    'adwordsConversion_label': 'saxOCKX7vFkQtbzy_gM'
});

<?php $this->headScript()->captureEnd(); ?>


<?php /* MOVED TO GTM
<!-- Google Code for SCNEO Free Alerts - Mobile Confirmed Conversion Page -->
<script type="text/javascript">
var google_conversion_id = 1071423029;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "saxOCKX7vFkQtbzy_gM";
var google_remarketing_only = false;
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1071423029/?label=saxOCKX7vFkQtbzy_gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
*/ ?>