<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Confirmed
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem selected"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>

<!-- Begin Module -->
<div class="cm decorated padded">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Setup Alerts</td>
                    <td class="sep"></td>
                    <td class="mn2">Receive Free Alerts Via Text Message</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd">
        <p>Enter the confirmation code you just received on your mobile phone. Once you have entered the confirmation code below, simply hit the "Confirm Code" button and you're done! You will now be all set to start receiving the <strong>SmallCap Network Elite Opportunity Free Mobile Text and Email Alerts</strong>.</p>


<div style="width:400px; margin: 0 auto;">
<form id="alert_form" name="alert_form" enctype="application/x-www-form-urlencoded" method="POST" action="/member/scneol/mobile/" class="form" onSubmit="return (YAHOO.viame.vivin_regula.validate(this, { groups: [regula.Group.alert_form] }) && YAHOO.viame.dubsub.check(this));">
<input type="hidden" name="vmpd_bpip" value="1" id="vmpd_bpip" />
<input type="hidden" name="vmpd_npr" value="1" id="vmpd_npr" />
<input type="hidden" name="id" value="<?= $this->params->id ?>" id="id" />
<input type="hidden" name="email" value="<?= $this->params->email ?>" id="email" />
<input type="hidden" name="mobile" value="<?= $this->params->mobile ?>" id="mobile" />
  <dl class="zend_form">
    <dt id="main-label">&#160;</dt>
    <dd id="main-element">
      <fieldset id="fieldset-main">
        <dl>
          <dt id="confirm-label">
            <label for="confirm" class="required">Confirmation Code</label>
          </dt>
          <dd id="confirm-element">
            <input type="text" name="confirm" id="confirm" value="" maxlength="256" class="regula-validation" data-constraints="@Required(label=&quot;confirmation code&quot;, message=&quot;The {label} field cannot be empty.&quot;, groups=[alert_form])" />
          </dd>
        </dl>
      </fieldset>
    </dd>
    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <dt id="submit-label">&#160;</dt>
          <dd id="submit-element">
            <input type="submit" name="submit" id="submit" value="Confirm Code" />
          </dd>
        </dl>
      </fieldset>
    </dd>
    <dt id="hidden-label">&#160;</dt>
    <dd id="hidden-element">
      <fieldset id="fieldset-hidden">
        <dl>
          <dt id="vmpd_nar-label">&#160;</dt>
          <dd id="vmpd_nar-element">
            <input type="hidden" name="vmpd_nar" value="1" id="vmpd_nar" />
          </dd>
          <dt id="redirect-label">&#160;</dt>
          <dd id="redirect-element">
            <input type="hidden" name="redirect" value="" id="redirect" />
          </dd>
        </dl>
      </fieldset>
    </dd>
  </dl>
</form>
</div>




    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
    <span class="icon"></span>
</div>
<!-- End Module -->