<h1><?= $this->escape(isset($this->internal->target->currentModule->display) && $this->internal->target->currentModule->display ? $this->internal->target->currentModule->display : $this->internal->target->currentModule->m_display) ?></h1>

<?php if (!$this->masked && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_WRITE)) { ?>
<p><a href="<?= $this->internal->target->pre ?>/portfolio/create/p/mid/<?= $this->internal->params->mid ?>/">Create New Portfolio</a></p>
<?php } ?>

<?php
foreach ($this->paginator as $object) {
    if ($this->internal->target->acl->owner ||
        $object->allowed === null ||
        $object->show_on_fail ||
        ($object->allowed && ($object->privilege >= ViaMe_Controller_Action::ACL_READ)) ||
        ($this->internal->target->acl->recursive && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_READ))) {
            
        // Create the link
        $link = '/' . $this->SEO_Urlify($object->title) . '/s';
        if ($this->masked) {
            $link .= $this->internal->target->pre . '/portfolio/view/p/mid/' . $this->masked . '/id/' . $object->counter . '/';
        }
        else {
            if ($object->com_id && ((isset($this->internal->params->com_id) && $this->internal->params->com_id) || $object->com_id != $this->internal->community->id)) { $link .= '/com/' . $object->com_id; }
            elseif ($object->net_id) { $link .= '/net/' . $object->net_id; }
            elseif ($object->via_id) { $link .= '/via/' . $object->via_id; }
            
            $link .= '/portfolio/view/p/mid/' . $object->matrix_counter . '/id/' . $object->counter . '/';
        }
?>

<div class="<?= $module ?> <?= ($counter % 2) ? 'odd' : 'even' ?><?= ($counter == 1) ? ' firstitem' : (($counter == count($this->objects)) ? ' lastitem' : '') ?><?= ($object->active == false ? ' draftitem' : '') ?><?= ($object->published_display_activated == false ? ' futureitem' : '') ?><?= ($object->published_display_expired == true ? ' expireditem' : '') ?>">

    <h2 class="title"><a href="<?= $link ?>"><?= $this->escape($object->title) ?></a><?= ($object->active == false ? ' <span class="drafttype">(Draft)</span>' : '') ?><?= ($object->published_display_activated == false ? ' <span class="futuretype">(Future)</span>' : '') ?><?= ($object->published_display_expired == true ? ' <span class="expiredtype">(Expired)</span>' : '') ?></h2>

<blockquote>
<?php if ($this->internal->target->currentModule->interactive && ($this->masked ? $this->portfolio->x_interactive : true)) { ?>
    <p class="interact"><a href="<?= $link ?>#comments_list"><?= $object->total_comments_count ?> Comment(s)</a> - Average Rating : <?= ($object->rating ? $object->rating : 'N/A') ?></p>
<?php } ?>
    <p class="datetime">
<?php
    $date = new Zend_Date();
    $date->set($object->published_display_date, Zend_Date::ISO_8601);
    if (isset($this->internal->member)) {
        $date->setTimezone($this->internal->member->timezone);
    }
    echo $date->toString('EEEE  MMMM d, YYY h:mm a z');
?>
    </p>
    
    <p>By <?= $this->ProfileDisplay(array('profile' => $object, 'internal' => $this->internal)) ?></p>
    
    <?= isset($object->summary) && $object->summary ? '<p>'. $this->escape($object->summary) . '</p>' : '' ?>
    
    <p><a href="<?= $link ?>">&raquo; <?= $this->escape($object->more_link ? $object->more_link : 'More') ?></a></p>
</blockquote>

</div>
<?php
    }
}
?>


<?php echo $this->paginationControl($this->paginator, 'Sliding', 'index/paginator.phtml', array('internal' => $this->internal)); ?>