DROP TABLE IF EXISTS system_languages CASCADE; -- CASCADE will drop all references to this table

CREATE TABLE system_languages (
    id                  bigserial PRIMARY KEY,
    creation            timestamp WITH TIME ZONE NOT NULL DEFAULT now(),

    code                varchar(8) NOT NULL,
    language            varchar(64) NOT NULL,
    
    orderby             real,
    
    updated             timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    active              bool DEFAULT 't' -- NULL=created but not yet active and not deactivated
);

-- Index on ID is automatically created by PRIMARY KEY
CREATE UNIQUE INDEX system_languages_language_x ON system_languages (language);
CREATE UNIQUE INDEX system_languages_code_x ON system_languages (code);
--CREATE INDEX system_languages_id_code_x ON system_languages (id, code);

ALTER TABLE public.system_languages OWNER TO vmdbuser;
ALTER TABLE public.system_languages_id_seq OWNER TO vmdbuser;

--Update the updated field on updates
CREATE TRIGGER "system_languages_updated_trigger" BEFORE UPDATE ON "system_languages" FOR EACH ROW EXECUTE PROCEDURE "current_updated" ();


----------------------------------------------------------------------------------------------------


INSERT INTO system_languages (code, language, orderby, active) VALUES ('ab', 'Abkhazian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ace', 'Achinese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ach', 'Acoli', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ada', 'Adangme', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ady', 'Adyghe', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('aa', 'Afar', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('afh', 'Afrihili', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('af', 'Afrikaans', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('afa', 'Afro-Asiatic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ain', 'Ainu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ak', 'Akan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('akk', 'Akkadian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sq', 'Albanian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ale', 'Aleut', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('alg', 'Algonquian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tut', 'Altaic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('am', 'Amharic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('egy', 'Ancient Egyptian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('grc', 'Ancient Greek', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('anp', 'Angika', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('apa', 'Apache Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ar', 'Arabic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('an', 'Aragonese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('arc', 'Aramaic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('arp', 'Arapaho', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('arn', 'Araucanian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('arw', 'Arawak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hy', 'Armenian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rup', 'Aromanian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('art', 'Artificial Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('as', 'Assamese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ast', 'Asturian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ath', 'Athapascan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cch', 'Atsam', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('en_AU', 'Australian English', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('aus', 'Australian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('de_AT', 'Austrian German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('map', 'Austronesian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('av', 'Avaric', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ae', 'Avestan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('awa', 'Awadhi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ay', 'Aymara', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('az', 'Azerbaijani', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ban', 'Balinese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bat', 'Baltic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bal', 'Baluchi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bm', 'Bambara', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bai', 'Bamileke Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bad', 'Banda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bnt', 'Bantu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bas', 'Basa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ba', 'Bashkir', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('eu', 'Basque', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('btk', 'Batak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bej', 'Beja', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('be', 'Belarusian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bem', 'Bemba', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bn', 'Bengali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ber', 'Berber', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bho', 'Bhojpuri', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bh', 'Bihari', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bik', 'Bikol', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bin', 'Bini', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bi', 'Bislama', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('byn', 'Blin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zbl', 'Blissymbols', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bs', 'Bosnian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bra', 'Braj', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pt_BR', 'Brazilian Portuguese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('br', 'Breton', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('en_GB', 'British English', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bug', 'Buginese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bg', 'Bulgarian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bua', 'Buriat', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('my', 'Burmese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cad', 'Caddo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('en_CA', 'Canadian English', 10, 't');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fr_CA', 'Canadian French', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('car', 'Carib', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ca', 'Catalan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cau', 'Caucasian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ceb', 'Cebuano', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cel', 'Celtic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cai', 'Central American Indian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chg', 'Chagatai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cmc', 'Chamic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ch', 'Chamorro', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ce', 'Chechen', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chr', 'Cherokee', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chy', 'Cheyenne', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chb', 'Chibcha', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zh', 'Chinese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chn', 'Chinook Jargon', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chp', 'Chipewyan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cho', 'Choctaw', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cu', 'Church Slavic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chk', 'Chuukese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cv', 'Chuvash', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nwc', 'Classical Newari', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('syc', 'Classical Syriac', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cop', 'Coptic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kw', 'Cornish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('co', 'Corsican', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cr', 'Cree', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mus', 'Creek', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('crp', 'Creole or Pidgin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('crh', 'Crimean Turkish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hr', 'Croatian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cus', 'Cushitic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cs', 'Czech', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dak', 'Dakota', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('da', 'Danish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dar', 'Dargwa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('day', 'Dayak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('del', 'Delaware', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('din', 'Dinka', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dv', 'Divehi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('doi', 'Dogri', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dgr', 'Dogrib', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dra', 'Dravidian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dua', 'Duala', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nl', 'Dutch', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dyu', 'Dyula', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dz', 'Dzongkha', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('frs', 'Eastern Frisian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('efi', 'Efik', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('eka', 'Ekajuk', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('elx', 'Elamite', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('en', 'English', 10, 't');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cpe', 'English-based Creole or Pidgin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('myv', 'Erzya', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('eo', 'Esperanto', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('et', 'Estonian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ee', 'Ewe', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ewo', 'Ewondo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fan', 'Fang', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fat', 'Fanti', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fo', 'Faroese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fj', 'Fijian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fil', 'Filipino', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fi', 'Finnish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fiu', 'Finno-Ugrian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nl_BE', 'Flemish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fon', 'Fon', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fr', 'French', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cpf', 'French-based Creole or Pidgin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fur', 'Friulian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ff', 'Fulah', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gaa', 'Ga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gl', 'Galician', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lg', 'Ganda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gay', 'Gayo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gba', 'Gbaya', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gez', 'Geez', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ka', 'Georgian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('de', 'German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gem', 'Germanic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gil', 'Gilbertese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gon', 'Gondi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gor', 'Gorontalo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('got', 'Gothic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('grb', 'Grebo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('el', 'Greek', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gn', 'Guarani', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gu', 'Gujarati', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gwi', 'Gwichʼin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hai', 'Haida', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ht', 'Haitian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ha', 'Hausa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('haw', 'Hawaiian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('he', 'Hebrew', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hz', 'Herero', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hil', 'Hiligaynon', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('him', 'Himachali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hi', 'Hindi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ho', 'Hiri Motu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hit', 'Hittite', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hmn', 'Hmong', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hu', 'Hungarian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hup', 'Hupa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('iba', 'Iban', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pt_PT', 'Iberian Portuguese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('es_ES', 'Iberian Spanish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('is', 'Icelandic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('io', 'Ido', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ig', 'Igbo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ijo', 'Ijo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ilo', 'Iloko', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('smn', 'Inari Sami', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('inc', 'Indic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ine', 'Indo-European Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('id', 'Indonesian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('inh', 'Ingush', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ia', 'Interlingua', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ie', 'Interlingue', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('iu', 'Inuktitut', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ik', 'Inupiaq', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ira', 'Iranian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ga', 'Irish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('iro', 'Iroquoian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('it', 'Italian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ja', 'Japanese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('jv', 'Javanese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kaj', 'Jju', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('jrb', 'Judeo-Arabic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('jpr', 'Judeo-Persian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kbd', 'Kabardian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kab', 'Kabyle', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kac', 'Kachin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kl', 'Kalaallisut', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('xal', 'Kalmyk', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kam', 'Kamba', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kn', 'Kannada', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kr', 'Kanuri', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kaa', 'Kara-Kalpak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('krc', 'Karachay-Balkar', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('krl', 'Karelian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kar', 'Karen', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ks', 'Kashmiri', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('csb', 'Kashubian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kaw', 'Kawi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kk', 'Kazakh', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kha', 'Khasi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('km', 'Khmer', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('khi', 'Khoisan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kho', 'Khotanese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ki', 'Kikuyu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kmb', 'Kimbundu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rw', 'Kinyarwanda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ky', 'Kirghiz', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tlh', 'Klingon', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kv', 'Komi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kg', 'Kongo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kok', 'Konkani', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ko', 'Korean', 10, 't');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kfo', 'Koro', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kos', 'Kosraean', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kpe', 'Kpelle', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kro', 'Kru', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kj', 'Kuanyama', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kum', 'Kumyk', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ku', 'Kurdish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kru', 'Kurukh', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kut', 'Kutenai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lad', 'Ladino', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lah', 'Lahnda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lam', 'Lamba', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lo', 'Lao', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('la', 'Latin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('es_419', 'Latin American Spanish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lv', 'Latvian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lez', 'Lezghian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('li', 'Limburgish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ln', 'Lingala', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lt', 'Lithuanian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('jbo', 'Lojban', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nds', 'Low German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dsb', 'Lower Sorbian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('loz', 'Lozi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lu', 'Luba-Katanga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lua', 'Luba-Lulua', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lui', 'Luiseno', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('smj', 'Lule Sami', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lun', 'Lunda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('luo', 'Luo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lus', 'Lushai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lb', 'Luxembourgish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mk', 'Macedonian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mad', 'Madurese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mag', 'Magahi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mai', 'Maithili', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mak', 'Makasar', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mg', 'Malagasy', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ms', 'Malay', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ml', 'Malayalam', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mt', 'Maltese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mnc', 'Manchu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mdr', 'Mandar', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('man', 'Mandingo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mni', 'Manipuri', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mno', 'Manobo Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gv', 'Manx', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mi', 'Maori', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mr', 'Marathi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('chm', 'Mari', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mh', 'Marshallese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mwr', 'Marwari', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mas', 'Masai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('myn', 'Mayan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('men', 'Mende', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mic', 'Micmac', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('dum', 'Middle Dutch', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('enm', 'Middle English', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('frm', 'Middle French', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gmh', 'Middle High German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mga', 'Middle Irish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('min', 'Minangkabau', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mwl', 'Mirandese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mis', 'Miscellaneous Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('moh', 'Mohawk', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mdf', 'Moksha', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mo', 'Moldavian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mkh', 'Mon-Khmer Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('lol', 'Mongo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mn', 'Mongolian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mos', 'Mossi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mul', 'Multiple Languages', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('mun', 'Munda Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nah', 'Nahuatl', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('na', 'Nauru', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nv', 'Navajo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ng', 'Ndonga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nap', 'Neapolitan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ne', 'Nepali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('new', 'Newari', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nia', 'Nias', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nic', 'Niger-Kordofanian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ssa', 'Nilo-Saharan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('niu', 'Niuean', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zxx', 'No linguistic content', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nog', 'Nogai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nai', 'North American Indian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nd', 'North Ndebele', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('frr', 'Northern Frisian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('se', 'Northern Sami', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nso', 'Northern Sotho', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('no', 'Norwegian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nb', 'Norwegian Bokmål', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nn', 'Norwegian Nynorsk', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nub', 'Nubian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nym', 'Nyamwezi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ny', 'Nyanja', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nyn', 'Nyankole', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tog', 'Nyasa Tonga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nyo', 'Nyoro', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nzi', 'Nzima', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nqo', 'N’Ko', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('oc', 'Occitan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('oj', 'Ojibwa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ang', 'Old English', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fro', 'Old French', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('goh', 'Old High German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sga', 'Old Irish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('non', 'Old Norse', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('peo', 'Old Persian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pro', 'Old Provençal', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('or', 'Oriya', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('om', 'Oromo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('osa', 'Osage', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('os', 'Ossetic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('oto', 'Otomian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ota', 'Ottoman Turkish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pal', 'Pahlavi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pau', 'Palauan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pi', 'Pali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pam', 'Pampanga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pag', 'Pangasinan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pap', 'Papiamento', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('paa', 'Papuan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ps', 'Pashto', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fa', 'Persian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('phi', 'Philippine Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('phn', 'Phoenician', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pon', 'Pohnpeian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pl', 'Polish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pt', 'Portuguese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cpp', 'Portuguese-based Creole or Pidgin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pra', 'Prakrit Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('pa', 'Punjabi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('qu', 'Quechua', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('raj', 'Rajasthani', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rap', 'Rapanui', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rar', 'Rarotongan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rm', 'Rhaeto-Romance', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('roa', 'Romance Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ro', 'Romanian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rom', 'Romany', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('root', 'Root', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('rn', 'Rundi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ru', 'Russian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sal', 'Salishan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sam', 'Samaritan Aramaic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('smi', 'Sami Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sm', 'Samoan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sad', 'Sandawe', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sg', 'Sango', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sa', 'Sanskrit', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sat', 'Santali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sc', 'Sardinian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sas', 'Sasak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sco', 'Scots', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gd', 'Scottish Gaelic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sel', 'Selkup', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sem', 'Semitic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sr', 'Serbian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sh', 'Serbo-Croatian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('srr', 'Serer', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('shn', 'Shan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sn', 'Shona', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ii', 'Sichuan Yi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('scn', 'Sicilian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sid', 'Sidamo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sgn', 'Sign Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bla', 'Siksika', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zh_Hans', 'Simplified Chinese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sd', 'Sindhi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('si', 'Sinhalese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sit', 'Sino-Tibetan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sio', 'Siouan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sms', 'Skolt Sami', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('den', 'Slave', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sla', 'Slavic Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sk', 'Slovak', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sl', 'Slovenian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sog', 'Sogdien', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('so', 'Somali', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('son', 'Songhai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('snk', 'Soninke', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('wen', 'Sorbian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sai', 'South American Indian Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('nr', 'South Ndebele', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('alt', 'Southern Altai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sma', 'Southern Sami', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('st', 'Southern Sotho', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('es', 'Spanish', 10, 't');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('srn', 'Sranan Tongo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('suk', 'Sukuma', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sux', 'Sumerian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('su', 'Sundanese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sus', 'Susu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sw', 'Swahili', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ss', 'Swati', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sv', 'Swedish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fr_CH', 'Swiss French', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('gsw', 'Swiss German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('de_CH', 'Swiss High German', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('syr', 'Syriac', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tl', 'Tagalog', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ty', 'Tahitian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tai', 'Tai Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tg', 'Tajik', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tmh', 'Tamashek', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ta', 'Tamil', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tt', 'Tatar', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('te', 'Telugu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ter', 'Tereno', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tet', 'Tetum', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('th', 'Thai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('bo', 'Tibetan', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tig', 'Tigre', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ti', 'Tigrinya', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tem', 'Timne', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tiv', 'Tiv', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tli', 'Tlingit', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tpi', 'Tok Pisin', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tkl', 'Tokelau', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('to', 'Tonga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zh_Hant', 'Traditional Chinese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tsi', 'Tsimshian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ts', 'Tsonga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tn', 'Tswana', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tum', 'Tumbuka', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tup', 'Tupi Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tr', 'Turkish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tk', 'Turkmen', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tvl', 'Tuvalu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tyv', 'Tuvinian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('tw', 'Twi', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('kcg', 'Tyap', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('en_US', 'U.S. English', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('udm', 'Udmurt', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('uga', 'Ugaritic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ug', 'Uighur', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('uk', 'Ukrainian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('umb', 'Umbundu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('und', 'Unknown or Invalid Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('hsb', 'Upper Sorbian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ur', 'Urdu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('uz', 'Uzbek', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('vai', 'Vai', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ve', 'Venda', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('vi', 'Vietnamese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('vo', 'Volapük', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('vot', 'Votic', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('wak', 'Wakashan Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('wal', 'Walamo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('wa', 'Walloon', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('war', 'Waray', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('was', 'Washo', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('cy', 'Welsh', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('fy', 'Western Frisian', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('wo', 'Wolof', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('xh', 'Xhosa', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('sah', 'Yakut', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('yao', 'Yao', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('yap', 'Yapese', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('yi', 'Yiddish', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('yo', 'Yoruba', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('ypk', 'Yupik Language', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('znd', 'Zande', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zap', 'Zapotec', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zza', 'Zaza', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zen', 'Zenaga', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('za', 'Zhuang', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zu', 'Zulu', 10, 'f');
INSERT INTO system_languages (code, language, orderby, active) VALUES ('zun', 'Zuni', 10, 'f');