DROP TABLE IF EXISTS system_timezones CASCADE; -- CASCADE will drop all references to this table

CREATE TABLE system_timezones (
    id                  bigserial PRIMARY KEY,
    creation            timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    
    timezone            varchar(64) NOT NULL,
    
    country_code        varchar(8)
    						REFERENCES system_countries (code)
    						ON DELETE CASCADE
    						ON UPDATE CASCADE,
    						
    orderby             real,
    
    updated             timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    active              bool DEFAULT 't' -- NULL=created but not yet active and not deactivated
);

-- Index on ID is automatically created by PRIMARY KEY
CREATE UNIQUE INDEX system_timezones_timezone_x ON system_timezones (timezone);
--CREATE INDEX system_timezones_id_timezone_x ON system_timezones (id, timezone);
--CREATE INDEX system_timezones_timezone_country_code_x ON system_timezones (timezone, country_code);

ALTER TABLE public.system_timezones OWNER TO vmdbuser;
ALTER TABLE public.system_timezones_id_seq OWNER TO vmdbuser;

--Update the updated field on updates
CREATE TRIGGER "system_timezones_updated_trigger" BEFORE UPDATE ON "system_timezones" FOR EACH ROW EXECUTE PROCEDURE "current_updated" ();

-- Check timezone TRIGGER
CREATE OR REPLACE FUNCTION "check_timezone_name" () RETURNS trigger AS $$
  DECLARE
    status      boolean;
  BEGIN
    SELECT true INTO status FROM pg_timezone_names WHERE name=NEW.timezone LIMIT 1;
    IF (status ISNULL OR status != 't') THEN
      RAISE EXCEPTION 'Invalid timezone specified.';
    END IF;
    RETURN NEW;
  END;
$$ LANGUAGE 'plpgsql';
-- Moved this trigger to the end (Initial Load Speed)
--CREATE TRIGGER "system_timezones_timezone_trigger" BEFORE INSERT OR UPDATE ON "system_timezones" FOR EACH ROW EXECUTE PROCEDURE "check_timezone_name" ();


----------------------------------------------------------------------------------------------------


-- Load Some Primary US
INSERT INTO system_timezones (timezone, orderby) VALUES ('US/Pacific', 10);
INSERT INTO system_timezones (timezone, orderby) VALUES ('US/Mountain', 20);
INSERT INTO system_timezones (timezone, orderby) VALUES ('US/Central', 20);
INSERT INTO system_timezones (timezone, orderby) VALUES ('US/Eastern', 20);
-- Load the Rest of the US
INSERT INTO system_timezones (timezone, orderby) SELECT name, 20 FROM pg_timezone_names WHERE name NOT IN (SELECT timezone FROM system_timezones) AND name NOT LIKE 'US/Pacific%' AND name LIKE 'US/%' AND abbrev <> 'zzz' ORDER BY name;
-- Load the Rest of the World
INSERT INTO system_timezones (timezone, orderby) SELECT name, 30 FROM pg_timezone_names WHERE name NOT IN (SELECT timezone FROM system_timezones) AND name !~ '^(CET|CST|EET|EST|Etc|GB|GMT|HST|MET|MST|Navajo|NZ|PRC|PST|UCT|US|UTC|Universal|W-SU|WET|Zulu|posixrules)' AND abbrev <> 'zzz' ORDER BY name;
-- Load the Etc/GMT
INSERT INTO system_timezones (timezone, orderby) SELECT name, 40 FROM pg_timezone_names WHERE name NOT IN (SELECT timezone FROM system_timezones) AND  name ~* '^Etc/GMT' AND name <> 'Etc/GMT+0' AND name <> 'Etc/GMT-0' AND name <> 'Etc/GMT0' AND abbrev <> 'zzz' ORDER BY utc_offset;
-- Load the Rest
INSERT INTO system_timezones (timezone, orderby) SELECT name, 50 FROM pg_timezone_names WHERE name NOT IN (SELECT timezone FROM system_timezones) AND  name !~ '^(Etc|GB|GMT|NZ|Navajo|US|posix)' AND abbrev <> 'zzz' ORDER BY name;


UPDATE system_timezones SET country_code='CI' WHERE timezone='Africa/Abidjan';
UPDATE system_timezones SET country_code='GH' WHERE timezone='Africa/Accra';
UPDATE system_timezones SET country_code='ET' WHERE timezone='Africa/Addis_Ababa';
UPDATE system_timezones SET country_code='DZ' WHERE timezone='Africa/Algiers';
UPDATE system_timezones SET country_code='ER' WHERE timezone='Africa/Asmara';
UPDATE system_timezones SET country_code='ER' WHERE timezone='Africa/Asmera';
UPDATE system_timezones SET country_code='ML' WHERE timezone='Africa/Bamako';
UPDATE system_timezones SET country_code='CF' WHERE timezone='Africa/Bangui';
UPDATE system_timezones SET country_code='GM' WHERE timezone='Africa/Banjul';
UPDATE system_timezones SET country_code='GW' WHERE timezone='Africa/Bissau';
UPDATE system_timezones SET country_code='MW' WHERE timezone='Africa/Blantyre';
UPDATE system_timezones SET country_code='CG' WHERE timezone='Africa/Brazzaville';
UPDATE system_timezones SET country_code='BI' WHERE timezone='Africa/Bujumbura';
UPDATE system_timezones SET country_code='EG' WHERE timezone='Africa/Cairo';
UPDATE system_timezones SET country_code='MA' WHERE timezone='Africa/Casablanca';
UPDATE system_timezones SET country_code='ES' WHERE timezone='Africa/Ceuta';
UPDATE system_timezones SET country_code='GN' WHERE timezone='Africa/Conakry';
UPDATE system_timezones SET country_code='SN' WHERE timezone='Africa/Dakar';
UPDATE system_timezones SET country_code='TZ' WHERE timezone='Africa/Dar_es_Salaam';
UPDATE system_timezones SET country_code='DJ' WHERE timezone='Africa/Djibouti';
UPDATE system_timezones SET country_code='CM' WHERE timezone='Africa/Douala';
UPDATE system_timezones SET country_code='EH' WHERE timezone='Africa/El_Aaiun';
UPDATE system_timezones SET country_code='SL' WHERE timezone='Africa/Freetown';
UPDATE system_timezones SET country_code='BW' WHERE timezone='Africa/Gaborone';
UPDATE system_timezones SET country_code='ZW' WHERE timezone='Africa/Harare';
UPDATE system_timezones SET country_code='ZA' WHERE timezone='Africa/Johannesburg';
UPDATE system_timezones SET country_code='UG' WHERE timezone='Africa/Kampala';
UPDATE system_timezones SET country_code='SD' WHERE timezone='Africa/Khartoum';
UPDATE system_timezones SET country_code='RW' WHERE timezone='Africa/Kigali';
UPDATE system_timezones SET country_code='CD' WHERE timezone='Africa/Kinshasa';
UPDATE system_timezones SET country_code='NG' WHERE timezone='Africa/Lagos';
UPDATE system_timezones SET country_code='GA' WHERE timezone='Africa/Libreville';
UPDATE system_timezones SET country_code='TG' WHERE timezone='Africa/Lome';
UPDATE system_timezones SET country_code='AO' WHERE timezone='Africa/Luanda';
UPDATE system_timezones SET country_code='CD' WHERE timezone='Africa/Lubumbashi';
UPDATE system_timezones SET country_code='ZM' WHERE timezone='Africa/Lusaka';
UPDATE system_timezones SET country_code='GQ' WHERE timezone='Africa/Malabo';
UPDATE system_timezones SET country_code='MZ' WHERE timezone='Africa/Maputo';
UPDATE system_timezones SET country_code='LS' WHERE timezone='Africa/Maseru';
UPDATE system_timezones SET country_code='SZ' WHERE timezone='Africa/Mbabane';
UPDATE system_timezones SET country_code='SO' WHERE timezone='Africa/Mogadishu';
UPDATE system_timezones SET country_code='LR' WHERE timezone='Africa/Monrovia';
UPDATE system_timezones SET country_code='KE' WHERE timezone='Africa/Nairobi';
UPDATE system_timezones SET country_code='TD' WHERE timezone='Africa/Ndjamena';
UPDATE system_timezones SET country_code='NE' WHERE timezone='Africa/Niamey';
UPDATE system_timezones SET country_code='MR' WHERE timezone='Africa/Nouakchott';
UPDATE system_timezones SET country_code='BF' WHERE timezone='Africa/Ouagadougou';
UPDATE system_timezones SET country_code='BJ' WHERE timezone='Africa/Porto-Novo';
UPDATE system_timezones SET country_code='ST' WHERE timezone='Africa/Sao_Tome';
UPDATE system_timezones SET country_code='ML' WHERE timezone='Africa/Timbuktu';
UPDATE system_timezones SET country_code='LY' WHERE timezone='Africa/Tripoli';
UPDATE system_timezones SET country_code='TN' WHERE timezone='Africa/Tunis';
UPDATE system_timezones SET country_code='NA' WHERE timezone='Africa/Windhoek';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Adak';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Anchorage';
UPDATE system_timezones SET country_code='AI' WHERE timezone='America/Anguilla';
UPDATE system_timezones SET country_code='AG' WHERE timezone='America/Antigua';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Araguaina';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Buenos_Aires';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Catamarca';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/ComodRivadavia';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Cordoba';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Jujuy';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/La_Rioja';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Mendoza';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Rio_Gallegos';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/San_Juan';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Tucuman';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Argentina/Ushuaia';
UPDATE system_timezones SET country_code='AW' WHERE timezone='America/Aruba';
UPDATE system_timezones SET country_code='PY' WHERE timezone='America/Asuncion';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Atikokan';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Atka';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Bahia';
UPDATE system_timezones SET country_code='BB' WHERE timezone='America/Barbados';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Belem';
UPDATE system_timezones SET country_code='BZ' WHERE timezone='America/Belize';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Blanc-Sablon';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Boa_Vista';
UPDATE system_timezones SET country_code='CO' WHERE timezone='America/Bogota';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Boise';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Buenos_Aires';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Cambridge_Bay';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Campo_Grande';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Cancun';
UPDATE system_timezones SET country_code='VE' WHERE timezone='America/Caracas';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Catamarca';
UPDATE system_timezones SET country_code='GF' WHERE timezone='America/Cayenne';
UPDATE system_timezones SET country_code='KY' WHERE timezone='America/Cayman';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Chicago';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Chihuahua';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Coral_Harbour';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Cordoba';
UPDATE system_timezones SET country_code='CR' WHERE timezone='America/Costa_Rica';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Cuiaba';
UPDATE system_timezones SET country_code='AN' WHERE timezone='America/Curacao';
UPDATE system_timezones SET country_code='GL' WHERE timezone='America/Danmarkshavn';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Dawson';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Dawson_Creek';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Denver';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Detroit';
UPDATE system_timezones SET country_code='DM' WHERE timezone='America/Dominica';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Edmonton';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Eirunepe';
UPDATE system_timezones SET country_code='SV' WHERE timezone='America/El_Salvador';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Ensenada';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Fort_Wayne';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Fortaleza';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Glace_Bay';
UPDATE system_timezones SET country_code='GL' WHERE timezone='America/Godthab';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Goose_Bay';
UPDATE system_timezones SET country_code='TC' WHERE timezone='America/Grand_Turk';
UPDATE system_timezones SET country_code='GD' WHERE timezone='America/Grenada';
UPDATE system_timezones SET country_code='GP' WHERE timezone='America/Guadeloupe';
UPDATE system_timezones SET country_code='GT' WHERE timezone='America/Guatemala';
UPDATE system_timezones SET country_code='EC' WHERE timezone='America/Guayaquil';
UPDATE system_timezones SET country_code='GY' WHERE timezone='America/Guyana';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Halifax';
UPDATE system_timezones SET country_code='CU' WHERE timezone='America/Havana';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Hermosillo';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Indianapolis';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Knox';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Marengo';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Petersburg';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Tell_City';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Vevay';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Vincennes';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indiana/Winamac';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Indianapolis';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Inuvik';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Iqaluit';
UPDATE system_timezones SET country_code='JM' WHERE timezone='America/Jamaica';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Jujuy';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Juneau';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Kentucky/Louisville';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Kentucky/Monticello';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Knox_IN';
UPDATE system_timezones SET country_code='BO' WHERE timezone='America/La_Paz';
UPDATE system_timezones SET country_code='PE' WHERE timezone='America/Lima';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Los_Angeles';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Louisville';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Maceio';
UPDATE system_timezones SET country_code='NI' WHERE timezone='America/Managua';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Manaus';
UPDATE system_timezones SET country_code='MQ' WHERE timezone='America/Martinique';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Mazatlan';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Mendoza';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Menominee';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Merida';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Mexico_City';
UPDATE system_timezones SET country_code='PM' WHERE timezone='America/Miquelon';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Moncton';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Monterrey';
UPDATE system_timezones SET country_code='UY' WHERE timezone='America/Montevideo';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Montreal';
UPDATE system_timezones SET country_code='MS' WHERE timezone='America/Montserrat';
UPDATE system_timezones SET country_code='BS' WHERE timezone='America/Nassau';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/New_York';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Nipigon';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Nome';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Noronha';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/North_Dakota/Center';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/North_Dakota/New_Salem';
UPDATE system_timezones SET country_code='PA' WHERE timezone='America/Panama';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Pangnirtung';
UPDATE system_timezones SET country_code='SR' WHERE timezone='America/Paramaribo';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Phoenix';
UPDATE system_timezones SET country_code='HT' WHERE timezone='America/Port-au-Prince';
UPDATE system_timezones SET country_code='TT' WHERE timezone='America/Port_of_Spain';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Porto_Acre';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Porto_Velho';
UPDATE system_timezones SET country_code='PR' WHERE timezone='America/Puerto_Rico';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Rainy_River';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Rankin_Inlet';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Recife';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Regina';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Resolute';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Rio_Branco';
UPDATE system_timezones SET country_code='AR' WHERE timezone='America/Rosario';
UPDATE system_timezones SET country_code='CL' WHERE timezone='America/Santiago';
UPDATE system_timezones SET country_code='DO' WHERE timezone='America/Santo_Domingo';
UPDATE system_timezones SET country_code='BR' WHERE timezone='America/Sao_Paulo';
UPDATE system_timezones SET country_code='GL' WHERE timezone='America/Scoresbysund';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Shiprock';
UPDATE system_timezones SET country_code='BL' WHERE timezone='America/St_Barthelemy';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/St_Johns';
UPDATE system_timezones SET country_code='KN' WHERE timezone='America/St_Kitts';
UPDATE system_timezones SET country_code='LC' WHERE timezone='America/St_Lucia';
UPDATE system_timezones SET country_code='VI' WHERE timezone='America/St_Thomas';
UPDATE system_timezones SET country_code='VC' WHERE timezone='America/St_Vincent';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Swift_Current';
UPDATE system_timezones SET country_code='HN' WHERE timezone='America/Tegucigalpa';
UPDATE system_timezones SET country_code='GL' WHERE timezone='America/Thule';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Thunder_Bay';
UPDATE system_timezones SET country_code='MX' WHERE timezone='America/Tijuana';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Toronto';
UPDATE system_timezones SET country_code='VG' WHERE timezone='America/Tortola';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Vancouver';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Whitehorse';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Winnipeg';
UPDATE system_timezones SET country_code='US' WHERE timezone='America/Yakutat';
UPDATE system_timezones SET country_code='CA' WHERE timezone='America/Yellowknife';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Casey';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Davis';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/DumontDUrville';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Mawson';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/McMurdo';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Palmer';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Rothera';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/South_Pole';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Syowa';
UPDATE system_timezones SET country_code='AQ' WHERE timezone='Antarctica/Vostok';
UPDATE system_timezones SET country_code='SJ' WHERE timezone='Arctic/Longyearbyen';
UPDATE system_timezones SET country_code='YE' WHERE timezone='Asia/Aden';
UPDATE system_timezones SET country_code='KZ' WHERE timezone='Asia/Almaty';
UPDATE system_timezones SET country_code='JO' WHERE timezone='Asia/Amman';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Anadyr';
UPDATE system_timezones SET country_code='KZ' WHERE timezone='Asia/Aqtau';
UPDATE system_timezones SET country_code='KZ' WHERE timezone='Asia/Aqtobe';
UPDATE system_timezones SET country_code='TM' WHERE timezone='Asia/Ashgabat';
UPDATE system_timezones SET country_code='TM' WHERE timezone='Asia/Ashkhabad';
UPDATE system_timezones SET country_code='IQ' WHERE timezone='Asia/Baghdad';
UPDATE system_timezones SET country_code='BH' WHERE timezone='Asia/Bahrain';
UPDATE system_timezones SET country_code='AZ' WHERE timezone='Asia/Baku';
UPDATE system_timezones SET country_code='TH' WHERE timezone='Asia/Bangkok';
UPDATE system_timezones SET country_code='LB' WHERE timezone='Asia/Beirut';
UPDATE system_timezones SET country_code='KG' WHERE timezone='Asia/Bishkek';
UPDATE system_timezones SET country_code='BN' WHERE timezone='Asia/Brunei';
UPDATE system_timezones SET country_code='IN' WHERE timezone='Asia/Calcutta';
UPDATE system_timezones SET country_code='MN' WHERE timezone='Asia/Choibalsan';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Chongqing';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Chungking';
UPDATE system_timezones SET country_code='LK' WHERE timezone='Asia/Colombo';
UPDATE system_timezones SET country_code='BD' WHERE timezone='Asia/Dacca';
UPDATE system_timezones SET country_code='SY' WHERE timezone='Asia/Damascus';
UPDATE system_timezones SET country_code='BD' WHERE timezone='Asia/Dhaka';
UPDATE system_timezones SET country_code='TL' WHERE timezone='Asia/Dili';
UPDATE system_timezones SET country_code='AE' WHERE timezone='Asia/Dubai';
UPDATE system_timezones SET country_code='TJ' WHERE timezone='Asia/Dushanbe';
UPDATE system_timezones SET country_code='PS' WHERE timezone='Asia/Gaza';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Harbin';
UPDATE system_timezones SET country_code='HK' WHERE timezone='Asia/Hong_Kong';
UPDATE system_timezones SET country_code='MN' WHERE timezone='Asia/Hovd';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Irkutsk';
UPDATE system_timezones SET country_code='TR' WHERE timezone='Asia/Istanbul';
UPDATE system_timezones SET country_code='ID' WHERE timezone='Asia/Jakarta';
UPDATE system_timezones SET country_code='ID' WHERE timezone='Asia/Jayapura';
UPDATE system_timezones SET country_code='IL' WHERE timezone='Asia/Jerusalem';
UPDATE system_timezones SET country_code='AF' WHERE timezone='Asia/Kabul';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Kamchatka';
UPDATE system_timezones SET country_code='PK' WHERE timezone='Asia/Karachi';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Kashgar';
UPDATE system_timezones SET country_code='NP' WHERE timezone='Asia/Katmandu';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Krasnoyarsk';
UPDATE system_timezones SET country_code='MY' WHERE timezone='Asia/Kuala_Lumpur';
UPDATE system_timezones SET country_code='MY' WHERE timezone='Asia/Kuching';
UPDATE system_timezones SET country_code='KW' WHERE timezone='Asia/Kuwait';
UPDATE system_timezones SET country_code='MO' WHERE timezone='Asia/Macao';
UPDATE system_timezones SET country_code='MO' WHERE timezone='Asia/Macau';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Magadan';
UPDATE system_timezones SET country_code='ID' WHERE timezone='Asia/Makassar';
UPDATE system_timezones SET country_code='PH' WHERE timezone='Asia/Manila';
UPDATE system_timezones SET country_code='OM' WHERE timezone='Asia/Muscat';
UPDATE system_timezones SET country_code='CY' WHERE timezone='Asia/Nicosia';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Novosibirsk';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Omsk';
UPDATE system_timezones SET country_code='KZ' WHERE timezone='Asia/Oral';
UPDATE system_timezones SET country_code='KH' WHERE timezone='Asia/Phnom_Penh';
UPDATE system_timezones SET country_code='ID' WHERE timezone='Asia/Pontianak';
UPDATE system_timezones SET country_code='KP' WHERE timezone='Asia/Pyongyang';
UPDATE system_timezones SET country_code='QA' WHERE timezone='Asia/Qatar';
UPDATE system_timezones SET country_code='KZ' WHERE timezone='Asia/Qyzylorda';
UPDATE system_timezones SET country_code='MM' WHERE timezone='Asia/Rangoon';
UPDATE system_timezones SET country_code='SA' WHERE timezone='Asia/Riyadh';
UPDATE system_timezones SET country_code='VN' WHERE timezone='Asia/Saigon';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Sakhalin';
UPDATE system_timezones SET country_code='UZ' WHERE timezone='Asia/Samarkand';
UPDATE system_timezones SET country_code='KR' WHERE timezone='Asia/Seoul';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Shanghai';
UPDATE system_timezones SET country_code='SG' WHERE timezone='Asia/Singapore';
UPDATE system_timezones SET country_code='TW' WHERE timezone='Asia/Taipei';
UPDATE system_timezones SET country_code='UZ' WHERE timezone='Asia/Tashkent';
UPDATE system_timezones SET country_code='GE' WHERE timezone='Asia/Tbilisi';
UPDATE system_timezones SET country_code='IR' WHERE timezone='Asia/Tehran';
UPDATE system_timezones SET country_code='IL' WHERE timezone='Asia/Tel_Aviv';
UPDATE system_timezones SET country_code='BT' WHERE timezone='Asia/Thimbu';
UPDATE system_timezones SET country_code='BT' WHERE timezone='Asia/Thimphu';
UPDATE system_timezones SET country_code='JP' WHERE timezone='Asia/Tokyo';
UPDATE system_timezones SET country_code='ID' WHERE timezone='Asia/Ujung_Pandang';
UPDATE system_timezones SET country_code='MN' WHERE timezone='Asia/Ulaanbaatar';
UPDATE system_timezones SET country_code='MN' WHERE timezone='Asia/Ulan_Bator';
UPDATE system_timezones SET country_code='CN' WHERE timezone='Asia/Urumqi';
UPDATE system_timezones SET country_code='LA' WHERE timezone='Asia/Vientiane';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Vladivostok';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Yakutsk';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Asia/Yekaterinburg';
UPDATE system_timezones SET country_code='AM' WHERE timezone='Asia/Yerevan';
UPDATE system_timezones SET country_code='PT' WHERE timezone='Atlantic/Azores';
UPDATE system_timezones SET country_code='BM' WHERE timezone='Atlantic/Bermuda';
UPDATE system_timezones SET country_code='ES' WHERE timezone='Atlantic/Canary';
UPDATE system_timezones SET country_code='CV' WHERE timezone='Atlantic/Cape_Verde';
UPDATE system_timezones SET country_code='FO' WHERE timezone='Atlantic/Faeroe';
UPDATE system_timezones SET country_code='FO' WHERE timezone='Atlantic/Faroe';
UPDATE system_timezones SET country_code='SJ' WHERE timezone='Atlantic/Jan_Mayen';
UPDATE system_timezones SET country_code='PT' WHERE timezone='Atlantic/Madeira';
UPDATE system_timezones SET country_code='IS' WHERE timezone='Atlantic/Reykjavik';
UPDATE system_timezones SET country_code='GS' WHERE timezone='Atlantic/South_Georgia';
UPDATE system_timezones SET country_code='SH' WHERE timezone='Atlantic/St_Helena';
UPDATE system_timezones SET country_code='FK' WHERE timezone='Atlantic/Stanley';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/ACT';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Adelaide';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Brisbane';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Broken_Hill';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Canberra';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Currie';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Darwin';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Eucla';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Hobart';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/LHI';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Lindeman';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Lord_Howe';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Melbourne';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/NSW';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/North';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Perth';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Queensland';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/South';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Sydney';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Tasmania';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Victoria';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/West';
UPDATE system_timezones SET country_code='AU' WHERE timezone='Australia/Yancowinna';
UPDATE system_timezones SET country_code='BR' WHERE timezone='Brazil/Acre';
UPDATE system_timezones SET country_code='BR' WHERE timezone='Brazil/DeNoronha';
UPDATE system_timezones SET country_code='BR' WHERE timezone='Brazil/East';
UPDATE system_timezones SET country_code='BR' WHERE timezone='Brazil/West';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Atlantic';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Central';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/East-Saskatchewan';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Eastern';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Mountain';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Newfoundland';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Pacific';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Saskatchewan';
UPDATE system_timezones SET country_code='CA' WHERE timezone='Canada/Yukon';
UPDATE system_timezones SET country_code='CL' WHERE timezone='Chile/Continental';
UPDATE system_timezones SET country_code='CL' WHERE timezone='Chile/EasterIsland';
UPDATE system_timezones SET country_code='CU' WHERE timezone='Cuba';
UPDATE system_timezones SET country_code='EG' WHERE timezone='Egypt';
UPDATE system_timezones SET country_code='IE' WHERE timezone='Eire';
UPDATE system_timezones SET country_code='NL' WHERE timezone='Europe/Amsterdam';
UPDATE system_timezones SET country_code='AD' WHERE timezone='Europe/Andorra';
UPDATE system_timezones SET country_code='GR' WHERE timezone='Europe/Athens';
UPDATE system_timezones SET country_code='IE' WHERE timezone='Europe/Belfast';
UPDATE system_timezones SET country_code='RS' WHERE timezone='Europe/Belgrade';
UPDATE system_timezones SET country_code='DE' WHERE timezone='Europe/Berlin';
UPDATE system_timezones SET country_code='SK' WHERE timezone='Europe/Bratislava';
UPDATE system_timezones SET country_code='BE' WHERE timezone='Europe/Brussels';
UPDATE system_timezones SET country_code='RO' WHERE timezone='Europe/Bucharest';
UPDATE system_timezones SET country_code='HU' WHERE timezone='Europe/Budapest';
UPDATE system_timezones SET country_code='MD' WHERE timezone='Europe/Chisinau';
UPDATE system_timezones SET country_code='DK' WHERE timezone='Europe/Copenhagen';
UPDATE system_timezones SET country_code='IE' WHERE timezone='Europe/Dublin';
UPDATE system_timezones SET country_code='GI' WHERE timezone='Europe/Gibraltar';
UPDATE system_timezones SET country_code='GG' WHERE timezone='Europe/Guernsey';
UPDATE system_timezones SET country_code='FI' WHERE timezone='Europe/Helsinki';
UPDATE system_timezones SET country_code='IM' WHERE timezone='Europe/Isle_of_Man';
UPDATE system_timezones SET country_code='TR' WHERE timezone='Europe/Istanbul';
UPDATE system_timezones SET country_code='JE' WHERE timezone='Europe/Jersey';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Europe/Kaliningrad';
UPDATE system_timezones SET country_code='UA' WHERE timezone='Europe/Kiev';
UPDATE system_timezones SET country_code='PT' WHERE timezone='Europe/Lisbon';
UPDATE system_timezones SET country_code='SI' WHERE timezone='Europe/Ljubljana';
UPDATE system_timezones SET country_code='GB' WHERE timezone='Europe/London';
UPDATE system_timezones SET country_code='LU' WHERE timezone='Europe/Luxembourg';
UPDATE system_timezones SET country_code='ES' WHERE timezone='Europe/Madrid';
UPDATE system_timezones SET country_code='MT' WHERE timezone='Europe/Malta';
UPDATE system_timezones SET country_code='AX' WHERE timezone='Europe/Mariehamn';
UPDATE system_timezones SET country_code='BY' WHERE timezone='Europe/Minsk';
UPDATE system_timezones SET country_code='MC' WHERE timezone='Europe/Monaco';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Europe/Moscow';
UPDATE system_timezones SET country_code='CY' WHERE timezone='Europe/Nicosia';
UPDATE system_timezones SET country_code='NO' WHERE timezone='Europe/Oslo';
UPDATE system_timezones SET country_code='FR' WHERE timezone='Europe/Paris';
UPDATE system_timezones SET country_code='ME' WHERE timezone='Europe/Podgorica';
UPDATE system_timezones SET country_code='CZ' WHERE timezone='Europe/Prague';
UPDATE system_timezones SET country_code='LV' WHERE timezone='Europe/Riga';
UPDATE system_timezones SET country_code='IT' WHERE timezone='Europe/Rome';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Europe/Samara';
UPDATE system_timezones SET country_code='SM' WHERE timezone='Europe/San_Marino';
UPDATE system_timezones SET country_code='BA' WHERE timezone='Europe/Sarajevo';
UPDATE system_timezones SET country_code='UA' WHERE timezone='Europe/Simferopol';
UPDATE system_timezones SET country_code='MK' WHERE timezone='Europe/Skopje';
UPDATE system_timezones SET country_code='BG' WHERE timezone='Europe/Sofia';
UPDATE system_timezones SET country_code='SE' WHERE timezone='Europe/Stockholm';
UPDATE system_timezones SET country_code='EE' WHERE timezone='Europe/Tallinn';
UPDATE system_timezones SET country_code='AL' WHERE timezone='Europe/Tirane';
UPDATE system_timezones SET country_code='UA' WHERE timezone='Europe/Uzhgorod';
UPDATE system_timezones SET country_code='LI' WHERE timezone='Europe/Vaduz';
UPDATE system_timezones SET country_code='VA' WHERE timezone='Europe/Vatican';
UPDATE system_timezones SET country_code='AT' WHERE timezone='Europe/Vienna';
UPDATE system_timezones SET country_code='LT' WHERE timezone='Europe/Vilnius';
UPDATE system_timezones SET country_code='RU' WHERE timezone='Europe/Volgograd';
UPDATE system_timezones SET country_code='PL' WHERE timezone='Europe/Warsaw';
UPDATE system_timezones SET country_code='HR' WHERE timezone='Europe/Zagreb';
UPDATE system_timezones SET country_code='UA' WHERE timezone='Europe/Zaporozhye';
UPDATE system_timezones SET country_code='CH' WHERE timezone='Europe/Zurich';
UPDATE system_timezones SET country_code='GB' WHERE timezone='Greenwich';
UPDATE system_timezones SET country_code='HK' WHERE timezone='Hongkong';
UPDATE system_timezones SET country_code='IS' WHERE timezone='Iceland';
UPDATE system_timezones SET country_code='MG' WHERE timezone='Indian/Antananarivo';
UPDATE system_timezones SET country_code='IO' WHERE timezone='Indian/Chagos';
UPDATE system_timezones SET country_code='CX' WHERE timezone='Indian/Christmas';
UPDATE system_timezones SET country_code='CC' WHERE timezone='Indian/Cocos';
UPDATE system_timezones SET country_code='KM' WHERE timezone='Indian/Comoro';
UPDATE system_timezones SET country_code='TF' WHERE timezone='Indian/Kerguelen';
UPDATE system_timezones SET country_code='SC' WHERE timezone='Indian/Mahe';
UPDATE system_timezones SET country_code='MV' WHERE timezone='Indian/Maldives';
UPDATE system_timezones SET country_code='MU' WHERE timezone='Indian/Mauritius';
UPDATE system_timezones SET country_code='YT' WHERE timezone='Indian/Mayotte';
UPDATE system_timezones SET country_code='RE' WHERE timezone='Indian/Reunion';
UPDATE system_timezones SET country_code='IR' WHERE timezone='Iran';
UPDATE system_timezones SET country_code='IL' WHERE timezone='Israel';
UPDATE system_timezones SET country_code='JM' WHERE timezone='Jamaica';
UPDATE system_timezones SET country_code='JP' WHERE timezone='Japan';
UPDATE system_timezones SET country_code='MH' WHERE timezone='Kwajalein';
UPDATE system_timezones SET country_code='LY' WHERE timezone='Libya';
UPDATE system_timezones SET country_code='MX' WHERE timezone='Mexico/BajaNorte';
UPDATE system_timezones SET country_code='MX' WHERE timezone='Mexico/BajaSur';
UPDATE system_timezones SET country_code='MX' WHERE timezone='Mexico/General';
UPDATE system_timezones SET country_code='WS' WHERE timezone='Pacific/Apia';
UPDATE system_timezones SET country_code='NZ' WHERE timezone='Pacific/Auckland';
UPDATE system_timezones SET country_code='NZ' WHERE timezone='Pacific/Chatham';
UPDATE system_timezones SET country_code='CL' WHERE timezone='Pacific/Easter';
UPDATE system_timezones SET country_code='VU' WHERE timezone='Pacific/Efate';
UPDATE system_timezones SET country_code='KI' WHERE timezone='Pacific/Enderbury';
UPDATE system_timezones SET country_code='TK' WHERE timezone='Pacific/Fakaofo';
UPDATE system_timezones SET country_code='FJ' WHERE timezone='Pacific/Fiji';
UPDATE system_timezones SET country_code='TV' WHERE timezone='Pacific/Funafuti';
UPDATE system_timezones SET country_code='EC' WHERE timezone='Pacific/Galapagos';
UPDATE system_timezones SET country_code='PF' WHERE timezone='Pacific/Gambier';
UPDATE system_timezones SET country_code='SB' WHERE timezone='Pacific/Guadalcanal';
UPDATE system_timezones SET country_code='GU' WHERE timezone='Pacific/Guam';
UPDATE system_timezones SET country_code='US' WHERE timezone='Pacific/Honolulu';
UPDATE system_timezones SET country_code='UM' WHERE timezone='Pacific/Johnston';
UPDATE system_timezones SET country_code='KI' WHERE timezone='Pacific/Kiritimati';
UPDATE system_timezones SET country_code='FM' WHERE timezone='Pacific/Kosrae';
UPDATE system_timezones SET country_code='MH' WHERE timezone='Pacific/Kwajalein';
UPDATE system_timezones SET country_code='MH' WHERE timezone='Pacific/Majuro';
UPDATE system_timezones SET country_code='PF' WHERE timezone='Pacific/Marquesas';
UPDATE system_timezones SET country_code='UM' WHERE timezone='Pacific/Midway';
UPDATE system_timezones SET country_code='NR' WHERE timezone='Pacific/Nauru';
UPDATE system_timezones SET country_code='NU' WHERE timezone='Pacific/Niue';
UPDATE system_timezones SET country_code='NF' WHERE timezone='Pacific/Norfolk';
UPDATE system_timezones SET country_code='NC' WHERE timezone='Pacific/Noumea';
UPDATE system_timezones SET country_code='AS' WHERE timezone='Pacific/Pago_Pago';
UPDATE system_timezones SET country_code='PW' WHERE timezone='Pacific/Palau';
UPDATE system_timezones SET country_code='PN' WHERE timezone='Pacific/Pitcairn';
UPDATE system_timezones SET country_code='FM' WHERE timezone='Pacific/Ponape';
UPDATE system_timezones SET country_code='PG' WHERE timezone='Pacific/Port_Moresby';
UPDATE system_timezones SET country_code='CK' WHERE timezone='Pacific/Rarotonga';
UPDATE system_timezones SET country_code='MP' WHERE timezone='Pacific/Saipan';
UPDATE system_timezones SET country_code='WS' WHERE timezone='Pacific/Samoa';
UPDATE system_timezones SET country_code='PF' WHERE timezone='Pacific/Tahiti';
UPDATE system_timezones SET country_code='KI' WHERE timezone='Pacific/Tarawa';
UPDATE system_timezones SET country_code='TO' WHERE timezone='Pacific/Tongatapu';
UPDATE system_timezones SET country_code='FM' WHERE timezone='Pacific/Truk';
UPDATE system_timezones SET country_code='UM' WHERE timezone='Pacific/Wake';
UPDATE system_timezones SET country_code='WF' WHERE timezone='Pacific/Wallis';
UPDATE system_timezones SET country_code='FM' WHERE timezone='Pacific/Yap';
UPDATE system_timezones SET country_code='PL' WHERE timezone='Poland';
UPDATE system_timezones SET country_code='PT' WHERE timezone='Portugal';
UPDATE system_timezones SET country_code='CN' WHERE timezone='ROC';
UPDATE system_timezones SET country_code='KP' WHERE timezone='ROK';
UPDATE system_timezones SET country_code='SG' WHERE timezone='Singapore';
UPDATE system_timezones SET country_code='TR' WHERE timezone='Turkey';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Alaska';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Aleutian';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Arizona';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Central';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/East-Indiana';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Eastern';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Hawaii';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Indiana-Starke';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Michigan';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Mountain';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Pacific';
UPDATE system_timezones SET country_code='US' WHERE timezone='US/Samoa';

CREATE TRIGGER "system_timezones_timezone_trigger" BEFORE INSERT OR UPDATE ON "system_timezones" FOR EACH ROW EXECUTE PROCEDURE "check_timezone_name" ();