DROP TABLE IF EXISTS system_countries CASCADE; -- CASCADE will drop all references to this table

CREATE TABLE system_countries (
    id                  bigserial PRIMARY KEY,
    creation            timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    
    code                varchar(8) NOT NULL CHECK (code = upper(code)),
    country             varchar(128) NOT NULL,
    
    orderby             real,
    
    updated             timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    active              bool DEFAULT 't' -- NULL=created but not yet active and not deactivated
);

-- Index on ID is automatically created by PRIMARY KEY
CREATE UNIQUE INDEX system_countries_country_x ON system_countries (country);
CREATE UNIQUE INDEX system_countries_code_x ON system_countries (code);
--CREATE INDEX system_countries_id_code_x ON system_countries (id, code);

ALTER TABLE public.system_countries OWNER TO vmdbuser;
ALTER TABLE public.system_countries_id_seq OWNER TO vmdbuser;

--Update the updated field on updates
CREATE TRIGGER "system_countries_updated_trigger" BEFORE UPDATE ON "system_countries" FOR EACH ROW EXECUTE PROCEDURE "current_updated" ();


----------------------------------------------------------------------------------------------------


INSERT INTO system_countries (code, country, active, orderby) VALUES ('AF', 'Afghanistan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AX', 'Aland Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AL', 'Albania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DZ', 'Algeria', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AS', 'American Samoa', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AD', 'Andorra', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AO', 'Angola', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AI', 'Anguilla', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AQ', 'Antarctica', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AG', 'Antigua and Barbuda', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AR', 'Argentina', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AM', 'Armenia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AW', 'Aruba', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AU', 'Australia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AT', 'Austria', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AZ', 'Azerbaijan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BS', 'Bahamas', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BH', 'Bahrain', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BD', 'Bangladesh', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BB', 'Barbados', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BY', 'Belarus', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BE', 'Belgium', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BZ', 'Belize', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BJ', 'Benin', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BM', 'Bermuda', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BT', 'Bhutan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BO', 'Bolivia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BA', 'Bosnia and Herzegovina', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BW', 'Botswana', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BV', 'Bouvet Island', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BR', 'Brazil', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BQ', 'British Antarctic Territory', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IO', 'British Indian Ocean Territory', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VG', 'British Virgin Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BN', 'Brunei', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BG', 'Bulgaria', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BF', 'Burkina Faso', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BI', 'Burundi', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KH', 'Cambodia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CM', 'Cameroon', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CA', 'Canada', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CT', 'Canton and Enderbury Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CV', 'Cape Verde', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KY', 'Cayman Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CF', 'Central African Republic', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TD', 'Chad', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CL', 'Chile', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CN', 'China', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CX', 'Christmas Island', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CC', 'Cocos Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CO', 'Colombia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KM', 'Comoros', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CG', 'Congo - Brazzaville', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CD', 'Congo - Kinshasa', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CK', 'Cook Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CR', 'Costa Rica', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HR', 'Croatia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CU', 'Cuba', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CY', 'Cyprus', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CZ', 'Czech Republic', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DK', 'Denmark', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DJ', 'Djibouti', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DM', 'Dominica', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DO', 'Dominican Republic', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NQ', 'Dronning Maud Land', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DD', 'East Germany', 'f', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TL', 'East Timor', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('EC', 'Ecuador', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('EG', 'Egypt', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SV', 'El Salvador', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GQ', 'Equatorial Guinea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ER', 'Eritrea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('EE', 'Estonia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ET', 'Ethiopia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('QU', 'European Union', 'f', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FK', 'Falkland Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FO', 'Faroe Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FJ', 'Fiji', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FI', 'Finland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FR', 'France', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GF', 'French Guiana', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PF', 'French Polynesia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TF', 'French Southern Territories', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FQ', 'French Southern and Antarctic Territories', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GA', 'Gabon', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GM', 'Gambia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GE', 'Georgia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('DE', 'Germany', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GH', 'Ghana', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GI', 'Gibraltar', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GR', 'Greece', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GL', 'Greenland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GD', 'Grenada', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GP', 'Guadeloupe', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GU', 'Guam', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GT', 'Guatemala', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GG', 'Guernsey', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GN', 'Guinea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GW', 'Guinea-Bissau', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GY', 'Guyana', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HT', 'Haiti', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HM', 'Heard Island and McDonald Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HN', 'Honduras', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HK', 'Hong Kong SAR China', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('HU', 'Hungary', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IS', 'Iceland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IN', 'India', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ID', 'Indonesia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IR', 'Iran', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IQ', 'Iraq', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IE', 'Ireland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IM', 'Isle of Man', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IL', 'Israel', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('IT', 'Italy', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CI', 'Ivory Coast', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('JM', 'Jamaica', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('JP', 'Japan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('JE', 'Jersey', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('JT', 'Johnston Island', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('JO', 'Jordan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KZ', 'Kazakhstan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KE', 'Kenya', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KI', 'Kiribati', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KW', 'Kuwait', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KG', 'Kyrgyzstan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LA', 'Laos', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LV', 'Latvia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LB', 'Lebanon', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LS', 'Lesotho', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LR', 'Liberia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LY', 'Libya', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LI', 'Liechtenstein', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LT', 'Lithuania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LU', 'Luxembourg', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MO', 'Macao SAR China', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MK', 'Macedonia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MG', 'Madagascar', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MW', 'Malawi', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MY', 'Malaysia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MV', 'Maldives', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ML', 'Mali', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MT', 'Malta', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MH', 'Marshall Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MQ', 'Martinique', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MR', 'Mauritania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MU', 'Mauritius', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('YT', 'Mayotte', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FX', 'Metropolitan France', 'f', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MX', 'Mexico', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('FM', 'Micronesia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MI', 'Midway Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MD', 'Moldova', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MC', 'Monaco', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MN', 'Mongolia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ME', 'Montenegro', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MS', 'Montserrat', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MA', 'Morocco', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MZ', 'Mozambique', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MM', 'Myanmar', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NA', 'Namibia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NR', 'Nauru', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NP', 'Nepal', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NL', 'Netherlands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AN', 'Netherlands Antilles', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NT', 'Neutral Zone', 'f', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NC', 'New Caledonia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NZ', 'New Zealand', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NI', 'Nicaragua', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NE', 'Niger', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NG', 'Nigeria', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NU', 'Niue', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NF', 'Norfolk Island', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KP', 'North Korea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VD', 'North Vietnam', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MP', 'Northern Mariana Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('NO', 'Norway', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('OM', 'Oman', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('QO', 'Outlying Oceania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PC', 'Pacific Islands Trust Territory', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PK', 'Pakistan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PW', 'Palau', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PS', 'Palestinian Territory', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PA', 'Panama', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PZ', 'Panama Canal Zone', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PG', 'Papua New Guinea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PY', 'Paraguay', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('YD', 'People''s Democratic Republic of Yemen', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PE', 'Peru', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PH', 'Philippines', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PN', 'Pitcairn', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PL', 'Poland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PT', 'Portugal', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PR', 'Puerto Rico', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('QA', 'Qatar', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('RE', 'Reunion', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('RO', 'Romania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('RU', 'Russia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('RW', 'Rwanda', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('BL', 'Saint Barthélemy', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SH', 'Saint Helena', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KN', 'Saint Kitts and Nevis', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LC', 'Saint Lucia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('MF', 'Saint Martin', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PM', 'Saint Pierre and Miquelon', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VC', 'Saint Vincent and the Grenadines', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('WS', 'Samoa', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SM', 'San Marino', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ST', 'Sao Tome and Principe', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SA', 'Saudi Arabia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SN', 'Senegal', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('RS', 'Serbia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CS', 'Serbia and Montenegro', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SC', 'Seychelles', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SL', 'Sierra Leone', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SG', 'Singapore', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SK', 'Slovakia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SI', 'Slovenia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SB', 'Solomon Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SO', 'Somalia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ZA', 'South Africa', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('KR', 'South Korea', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ES', 'Spain', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('LK', 'Sri Lanka', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SD', 'Sudan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SR', 'Suriname', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SJ', 'Svalbard and Jan Mayen', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SZ', 'Swaziland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SE', 'Sweden', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('CH', 'Switzerland', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SY', 'Syria', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TW', 'Taiwan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TJ', 'Tajikistan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TZ', 'Tanzania', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TH', 'Thailand', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TG', 'Togo', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TK', 'Tokelau', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TO', 'Tonga', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TT', 'Trinidad and Tobago', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TN', 'Tunisia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TR', 'Turkey', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TM', 'Turkmenistan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TC', 'Turks and Caicos Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('TV', 'Tuvalu', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('PU', 'U.S. Miscellaneous Pacific Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VI', 'U.S. Virgin Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('UG', 'Uganda', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('UA', 'Ukraine', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('SU', 'Union of Soviet Socialist Republics', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('AE', 'United Arab Emirates', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('GB', 'United Kingdom', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('US', 'United States', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('UM', 'United States Minor Outlying Islands', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ZZ', 'Unknown or Invalid Region', 'f', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('UY', 'Uruguay', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('UZ', 'Uzbekistan', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VU', 'Vanuatu', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VA', 'Vatican', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VE', 'Venezuela', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('VN', 'Vietnam', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('WK', 'Wake Island', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('WF', 'Wallis and Futuna', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('EH', 'Western Sahara', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('YE', 'Yemen', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ZM', 'Zambia', 't', 10);
INSERT INTO system_countries (code, country, active, orderby) VALUES ('ZW', 'Zimbabwe', 't', 10);