<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link href="<?= $this->internal->vars->static_host ?>/css/community/scn-china/stylesheet.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?= $this->internal->vars->static_host ?>/css/theme/fareast/stylesheet.css" media="screen" rel="stylesheet" type="text/css" title="Default" />
<style type="text/css" media="screen">
<!--
body { padding: 1em; }
-->
</style>
</head>

<body>

<center>
<!--Start Email-->
<table border="0" cellspacing="0" cellpadding="18" align="center" class="email" style="font-family: Arial, Helvetica, sans-serif; font-size: 13px; width: 560px; color: #333;">
    <tr>
        <td class="header" style="padding: 18px; border: 1px solid #cacaca; background-color: #ddd; background: url(<?= $this->internal->vars->static_host ?>/css/community/scn-china/assets/hd_bg.png); border-top: 1px solid #cacaca; border-top; -moz-border-radius-topleft: 10px; -moz-border-radius-topright: 10px; -webkit-border-top-left-radius-: 10px; -webkit-border-top-right-radius-: 10px;"><a href="http://china.smallcapnetwork.com" title="SmallCap Network China"><img src="<?= $this->internal->vars->static_host ?>/css/community/scn-china/assets/logo/logo.png" border="0" alt="SmallCap Network China Logo" /></a></td>
    </tr>
    <tr>
        <td class="subject" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; background-color: #efefef; color: #333; font-size: 14px; font-weight: bold;"><?= $this->layout()->subject ?></td>
    </tr>
    <tr>
        <td class="body" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/page_body_bg.gif) repeat-x 0 -1px;">

<?= $this->layout()->content ?>
        
        </td>
    </tr>
    <tr>
        <td class="footer" style="padding: 18px; border: 1px solid #cacaca; border-top: 0; text-align: center; font-size: 11px; color: #808080; -moz-border-radius-bottomleft: 10px; -moz-border-radius-bottomright: 10px; -webkit-border-bottom-left-radius-: 10px; -webkit-border-bottom-right-radius-: 10px;">Copyright &copy; 2001-<?= date('Y') ?> <a href="http://china.smallcapnetwork.com" title="SmallCap Network China">SmallCapNetwork.com</a> and TGR Group, LLC. All Rights Reserved.</td>
    </tr>
</table>
<!--End Email-->
</center>

</body>
</html>