<?= $this->docType() ?>

<?php
    #$this->headTitle('ViaMe');
    $this->headTitle()->setSeparator(' : ');

    $this->headMeta()->appendHttpEquiv('content-type', 'text/html; charset=UTF-8');
    //$this->headMeta()->appendHttpEquiv('content-language', 'en-US');
    //$this->headMeta()->appendHttpEquiv('refresh', '0; URL=http://www.yahoo.com');
    //$this->headMeta()->appendName('author', 'Author Name');
    //$this->headMeta()->appendName('copyright', 'Copyright by Author');
    //$this->headMeta()->appendName('description', 'This is the page meta description.');
    //$this->headMeta()->appendName('keywords', 'These, are, the, keywords');
    $this->headMeta()->appendName('cache-control', 'no-cache');
    $this->headMeta()->appendName('pragma', 'no-cache');
    $this->headMeta()->appendName('expires', 'Wed, 01 Jan 1997 00:00:00 GMT');
    $this->headMeta()->appendName('robots', 'all');
    
    $this->headMeta()->appendName('verify-v1', 'kjDzY/1ebs1MwOgwQLc340mULYcWjX4d1P5FNNyG+V8=');
    $this->headMeta()->appendName('verify-v1', 't7tidcmebhgxjef0FhGC4jFvmuSscR+G1jCBRc2JegE=');
    
    $this->headLink(array('rel' => 'icon', 'href' => $this->internal->vars->static_host . '/css/community/scn-china/assets/favicon.ico'));
    $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->internal->vars->static_host . '/css/community/scn-china/assets/favicon.ico'));
    
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/theme/fareast/stylesheet.css', 'screen', false, array('title' => 'Far East'));    
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/community/scn-china/stylesheet.css');
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/css/community/default/print.css', 'print');
    
    /* Yahoo CDN JavaScript Rollup - ADDED YUI 3.0 SEED FILE
    
        http://developer.yahoo.com/yui/articles/hosting/?animation&autocomplete&button&calendar&carousel&connection&connectioncore&container&containercore&cookie&datasource&dom&dragdrop&editor&element&event&menu&resize&selector&simpleeditor&tabview&utilities&yahoo&yahoo-dom-event&yuiloader&yuiloader-dom-event&MIN
        
        http://yui.yahooapis.com/combo?2.9.0/build/utilities/utilities.js&2.9.0/build/datasource/datasource-min.js&2.9.0/build/autocomplete/autocomplete-min.js&2.9.0/build/container/container-min.js&2.9.0/build/menu/menu-min.js&2.9.0/build/button/button-min.js&2.9.0/build/calendar/calendar-min.js&2.9.0/build/carousel/carousel-min.js&2.9.0/build/cookie/cookie-min.js&2.9.0/build/editor/editor-min.js&2.9.0/build/resize/resize-min.js&2.9.0/build/selector/selector-min.js&2.9.0/build/tabview/tabview-min.js&3.7.3/build/yui/yui-min.js
    */
    //$this->headScript()->prependFile('http://yui.yahooapis.com/combo?2.9.0/build/utilities/utilities.js&2.9.0/build/datasource/datasource-min.js&2.9.0/build/autocomplete/autocomplete-min.js&2.9.0/build/container/container-min.js&2.9.0/build/menu/menu-min.js&2.9.0/build/button/button-min.js&2.9.0/build/calendar/calendar-min.js&2.9.0/build/carousel/carousel-min.js&2.9.0/build/cookie/cookie-min.js&2.9.0/build/editor/editor-min.js&2.9.0/build/resize/resize-min.js&2.9.0/build/selector/selector-min.js&2.9.0/build/tabview/tabview-min.js&3.7.3/build/yui/yui-min.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui_combo_local.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui3/build/yui/yui-min.js');
    
    $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/vm/vm.js');
    $this->headScript()->appendFile($this->internal->vars->static_host . '/js/vm/yui/viame_form_helper.js');
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->render('../default/includes/header.phtml'); ?>
</head>

<body class="yui-skin-sam">

<!-- Begin SubLayout -->
<div class="page_body_internal">					
	<div id="bd"><div id="yui-main"><div class="yui-b">
		<div id="content_area" style="margin: 1em;"><?= str_replace('http://', 'https://', $this->layout()->content) ?></div>
	</div></div></div>
</div>
<!-- End SubLayout -->

<?= $this->inlineScript() ?>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-1218496-6");
pageTracker._setDomainName(".smallcapnetwork.com");
pageTracker._trackPageview();
} catch(err) {}</script>
    
<!-- Start Quantcast tag -->
<script type="text/javascript">
_qoptions={
qacct:"p-c8_asQOOYxhUo"
};
</script>
<script type="text/javascript" src="https://edge.quantserve.com/quant.js"></script>
<noscript>
<img src="https://pixel.quantserve.com/pixel/p-c8_asQOOYxhUo.gif" style="display: none;" border="0" height="1" width="1" alt="Quantcast"/>
</noscript>
<!-- End Quantcast tag -->

</body>
</html>