<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount > 1) { ?>
    <div class="paginator">
        
        <!-- First page link -->
        <?php if (isset($this->previous)) { ?>
          <a href="<?= $this->escape('?s=' . $this->internal->params->s . '&limit=' . $this->itemCountPerPage . '&page=' . $this->first) ?>">First</a>
        <?php } else { ?>
          <span class="disabled">First</span>
        <?php } ?>
        
        <!-- Previous page link -->
        <?php if (isset($this->previous)) { ?>
          <a href="<?= $this->escape('?s=' . $this->internal->params->s . '&limit=' . $this->itemCountPerPage . '&page=' . $this->previous) ?>">&laquo; Previous</a>
        <?php } else { ?>
          <span class="disabled">&laquo; Previous</span>
        <?php } ?>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page) {
            if ($page != $this->current) { ?>
          <a href="?<?= $this->escape((isset($this->internal->params->s) && $this->internal->params->s ? 's=' . $this->internal->params->s . '&' : '') . 'limit=' . $this->itemCountPerPage . '&page=' . $page) ?>"><?= $page ?></a>
        <?php } else { ?>
          <?= $page ?>
        <?php
            }
        } ?>
        
        <!-- Next page link -->
        <?php if (isset($this->next)) { ?>
          <a href="<?= $this->escape('?s=' . $this->internal->params->s . '&limit=' . $this->itemCountPerPage . '&page=' . $this->next) ?>">Next &raquo;</a>
        <?php } else { ?>
          <span class="disabled">Next &raquo;</span>
        <?php } ?>
        
        <!-- Last page link -->
        <?php if (isset($this->next)) { ?>
          <a href="<?= $this->escape('?s=' . $this->internal->params->s . '&limit=' . $this->itemCountPerPage . '&page=' . $this->last) ?>">Last</a>
        <?php } else { ?>
          <span class="disabled">Last</span>
        <?php } ?>
        
    </div>
<?php } ?>