<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Sign-Up Now...Free!
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem selected"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>

<table style="width: 100%;">
    <tr>
        <td style="vertical-align: top;"><div style="margin-right: 1em;">
 						
<!-- Begin Module -->
<div class="cm decorated">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1"><?= $this->internal->community->display ?> Registration!</td>
                    <td class="sep"></td>
                    <td class="mn2">Welcome<?= $this->fnwelcome ? ', ' . $this->escape($this->fnwelcome) : '' ?>!</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd padded">

<p class="welcome">
    Hi<?= $this->fnwelcome ? ', ' . $this->escape($this->fnwelcome) : '' ?>!
    We just need a little <?= ($_SERVER['QUERY_STRING'] || count($_POST)) ? 'more' : '' ?> information for you to join the <?= $this->internal->community->display ?> community.
</p>


<?php
if ($this->formErrors) {
    print '<ul class="errors" style="margin-bottom: 1em;">';
    foreach ($this->formErrors as $message) {
        print "<li>$message</li>\n";
    }
    print '</ul>';
}
?>

<?= $this->form ?>


    </div>
    <div class="ft">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
    </div>
    
    <span class="icon"></span>
</div>
<!-- End Module -->
 						
        </div></td>
        
        <td style="width: 240px; vertical-align: top;">

<!-- Begin Module -->
<div class="cm decorated">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Already a Member?</td>
                    <td class="sep"></td>
                    <td class="mn2"></td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd">

<form action="<?= $this->internal->target->pre ?>/member/login/p/vmpd_nar/1/" style="text-align: center; padding: 1em;"><input type="submit" class="big" value="Sign In" /></form>
<p style="font-style: italic;">If you have already registered, but are having issues with the verification process, <a href="/member/register/verify/">click here</a>.</p>

    </div>
    <div class="ft">
    	<div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1"></td>
                    <td class="sep"></td>
                    <td class="mn2"></td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
    </div>
    
    <span class="icon"></span>
</div>
<!-- End Module -->

        </td>
    </tr>
</table>

<?= $this->FormHelper(array('internal' => $this->internal)) ?>