<?php $this->placeholder('temp')->captureStart(); ?>
<p class="success">You have successfully verified your account and it is now active.</p>

<h2>Welcome to the <?= $this->internal->community->display ?> community! Get published now!</h2>

<table style="margin-top: 2em;">
    <tr>
        <td valign="top" style="width: 31%; padding-left: 55px; padding-right: 5px; background: url(<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/1.png) no-repeat;"><p><strong>Publish An Article</strong></p><p>Share your thoughts and opinions on your interests.</p></td>
        <td style="width: 2%; border-left: 1px dotted #999;">&nbsp;</td>
        <td valign="top" style="width: 31%; padding-left: 53px; padding-right: 5px; background: url(<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/2.png) no-repeat;"><p><strong>Publish An Analysis</strong></p><p>Create a customizable research report on stocks, mutual funds and other equities.</p></td>
        <td style="width: 2%; border-left: 1px dotted #999;">&nbsp;</td>
        <td valign="top" style="width: 31%; padding-left: 54px; background: url(<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/3.png) no-repeat;"><p><strong>Publish Stock Picks &amp; Ratings</strong></p><p>Let investors know which stocks you think are poised for big returns.</p></td>
    </tr>
</table>

<p style="text-align: center; margin-top: 3em;">
    <a href="<?= $this->internal->target->pre ?>/member/login/verify/vmpd_nar/1/?redirect=<?= '%2Fvia%2F' . $this->member_profile_id . '%2F' ?>"><img src="<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/start_publishing.png" alt="Start Publishing"></a>

<?php if (isset($this->internal->params->redirect) && $this->internal->params->redirect) { ?>
    <a href="<?= $this->internal->target->pre ?>/member/login/verify/vmpd_nar/1/?redirect=<?= $this->internal->params->redirect ?>" style="margin-left: 5em;"><img src="<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/continue.png" alt="Continue"></a>
<?php } ?>
</p>


<?php /* Already created the default modules in the verification
<p style="text-align: center; margin-top: 3em;"><a href="<?= $this->internal->target->pre ?>/member/login/verify/vmpd_nar/1/?redirect=%2Fvia%2F<?= $this->member_profile_id ?>%2Fprofile%2Fsetup%2Fp%2Fvmpd_nar%2F1%2F"><img src="<?= $this->internal->vars->static_host ?>/css/theme/default/assets/modules/member/register_verify/start_publishing.png"></a></p>

<p style="text-align: right; color: #ccc; margin-top: 3em;"><a href="<?= $this->internal->target->pre ?>/member/login/verify/vmpd_nar/1/<?= (isset($this->internal->params->redirect) && $this->internal->params->redirect ? '?redirect=' . $this->internal->params->redirect : '') ?>" style="color: #ccc;">Continue and bypass default module setup &raquo;</a></p>
*/ ?>

<?php /* Investing Channel Co-Registration
<hr />
<p style="margin-top: 1em; font-size: 16px;"><strong>Thank you for signing up today. Below are some free offers you might be interested in. Please understand that they are completely optional and don't require a credit card.</strong></p>
<?php
$partner_url = 'http://valid1.net/default.aspx?bdlid=1124&';
foreach (array('email' => 'email', 'first_name' => 'first_name', 'last_name' => 'last_name', 'postal_code' => 'zip', 'country' => 'country', 'dob' => 'date_of_birth', 'gender' => 'gender') as $key => $val) {
    if (isset($this->member->{$key}) && $this->member->{$key}) {
        $partner_url .= $val . '=' . urlencode($this->member->{$key}) . '&';
    }
}
$partner_url .= 'redirect_url=';

if (isset($this->internal->params->redirect) && $this->internal->params->redirect) {
    $partner_url .= $this->internal->params->redirect;
}
else {
    $partner_url .= '%2Fvia%2F' . $this->member_profile_id . '%2F';
}
?>
<iframe src ="<?= $partner_url ?>" width="100%" height="1200" align="middle" frameborder="0"></iframe>
*/ ?>

<?php $this->placeholder('temp')->captureEnd(); ?>

<?php
echo $this->CM(array(
    'class' => 'cm decorated plain successmessage',
    'hd' => 'Verification Successful',
    'hd2' => 'Thank you for verifying your account',
    'bd' => $this->placeholder('temp')
));
$this->placeholder('temp')->set(null);
?>