<div class="multistep_header">
    <table><tr>
        <td align="left" class="header">
            Confirm Request
        </td>
        <td align="right" class="steps">
            <table class="ind_steps"><tr>
                <td>
                    <div class="step firstitem"><span class="stepnumber">1</span>Enter Info</div>
                </td>
                <td>
                    <div class="step"><span class="stepnumber">2</span>Check Email</div>
                </td>
                <td>
                    <div class="step lastitem selected"><span class="stepnumber">3</span>Confirmation</div>
                </td>
            </tr></table>
        </td>
    </tr></table>
</div>

<?php
echo $this->CM(array(
    'class' => 'cm decorated padded',
    'hd' => 'Account Verification',
    'hd2' => 'Verify your newly registered account',
    'bd' => '<p>To have the verification key re-sent to you, please fill in the email field and leave the key field empty.</p>'
        . $this->render('form.phtml')
));
?>