<?php $this->placeholder('temp')->captureStart(); ?>
<ul>
    <li><a href="<?= $this->internal->target->pre ?>/member/update/account/">Update Member Settings</a></li>
    <li><a href="<?= $this->internal->target->pre ?>/member/update/password/">Change Password</a></li>
    <li><a href="<?= $this->internal->target->pre ?>/member/update/email/">Change Email</a></li>
    <li><a href="<?= $this->internal->target->pre ?>/member/reset/">Reset Password</a></li>
    <li><a href="<?= $this->internal->target->pre ?>/member/sociallogins/">Manage Social Logins</a></li>
</ul>
<?php $this->placeholder('temp')->captureEnd(); ?>

<?php
echo $this->CM(array(
    'class' => 'cm decorated padded',
    'hd' => 'Account Information',
    'bd' => $this->placeholder('temp')
));
$this->placeholder('temp')->set(null);
?>