<h1><?= isset($this->page_title) && $this->page_title ? $this->page_title : 'Update Picture' ?></h1>

<form id="update_picture_form" enctype="multipart/form-data" method="post" class="form" action="?" onsubmit="this.file_upload.disabled=false; return (YAHOO.viame.vivin_regula.validate(this, { groups: [regula.Group.update_picture_form] }) && YAHOO.viame.dubsub.check(this));"><dl class="zend_form">
<?php /* = $this->form->getDisplayGroup('hidden') */ ?>

<table style="width: 100%;">
    <tr>
        <td style="width: 230px; min-width: 230px; vertical-align: top;">

<!-- Begin Options -->
<div class="cm decorated">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
        <div class="con">
        	<table class="table">

                <tr>

                    <td class="lt"></td>
                    <td class="mn1">Preview</td>
                    <td class="sep"></td>
                    <td class="mn2"></td>
                    <td class="rt"></td>
                </tr>
            </table>

        </div>
    </div>
    <div class="bd" style="padding: 1em 1em .5em 1em; text-align: center;">


        <div class="image_area" style="padding: 0; border-bottom: none;">
            <div class="headshot<?= !(isset($this->internal->target->space->picture_url) && $this->internal->target->space->picture_url) ? ' ' . $this->internal->target->type . '_default' : '' ?>">

<?php   if (isset($this->internal->target->space->picture_url) && $this->internal->target->space->picture_url) { ?>
                <img src="<?= (preg_match('#http://#i', $this->internal->target->space->picture_url) ? '' : $this->internal->config->upload->picture_server . '/') ?><?= $this->escape($this->internal->target->space->picture_url) ?>" width="128" />
<?php   } ?>

            </div>
        </div>
<?php   if (isset($this->internal->target->space->picture_url) && $this->internal->target->space->picture_url) { ?>
        <div style="margin-top: 1em;"><input type="submit" name="remove_picture" id="remove_picture" class="red" value="Remove Picture" /></div>
<?php   } ?>    

    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
</div>
<!-- End Options -->

        </td>
        <td style="vertical-align: top;"><div class="cm decorated" style="margin-left: 1em; padding: 1em;">
            <p>Select a picture that will best represent you or your space.  The <i>exact</i> size of the image does not matter, but <strong>sizing will be applied upon display</strong>. Lower resolution images may look distorted or pixelated when displayed.  <strong>Do not upload images containing celebrities, nudity or copyrighted images.</strong></p>
<?php
if ($this->formErrors) {
    print '<div class="errors"><ul>';
    foreach ($this->formErrors as $message) {
        print "<li>$message</li>\n";
    }
    print '</ul></div>';
}

echo $this->form;
?>

        </div></td>
    </tr>
</table>
</dl></form>

<?= $this->FormHelper(array('internal' => $this->internal)) ?>
