<?php
$VERSION = '20150515';

echo $this->docType();
?>

<?php
    // Capture the body first
    $this->placeholder('body')->set($this->render('includes/body.phtml'));
    
    $this->headTitle()->setSeparator(' : ');
    
    $this->headMeta()->appendHttpEquiv('content-type', 'text/html; charset=UTF-8');
    $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    $this->headMeta()->appendName('cache-control', 'no-cache');
    $this->headMeta()->appendName('pragma', 'no-cache');
    $this->headMeta()->appendName('expires', 'Wed, 01 Jan 1997 00:00:00 GMT');
    
    #$this->headMeta()->appendName('google-site-verification', 'Kw_IAust9ES4n-_pF8nfkQAvCt2e6Sih1xZ4EiUhlEA');
    #$this->headMeta()->appendName('msvalidate.01', 'A616F9628150988274D546584CA6856E');
    #$this->headMeta()->appendName('y_key', 'a0fd6bbee8c05e61');
    #try {
    #    // Have to catch exceptions thrown when wrong doctype
    #    $this->headMeta()->appendProperty('fb:page_id', '88202206436');
    #} catch (Exception $e) { }
        
    $this->headLink(array('rel' => 'icon', 'href' => $this->internal->vars->static_host . '/css/community/ninjaplays/assets/favicon.ico'));
    $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->internal->vars->static_host . '/css/community/ninjaplays/assets/favicon.ico'));
    
    // Reversed Order to keep print.css last if printing
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/js/jasny/css/jasny-bootstrap.min.css');
    #$this->headLink()->prependStylesheet('https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css');
    $this->headLink()->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css');
    $this->headLink()->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css');
    
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/community/ninjaplays/stylesheet.css?v=' . $VERSION);
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/theme/default/stylesheet.css?v=' . $VERSION, 'screen', false, array('title' => 'Default'));
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/community/default/stylesheet.css?v=' . $VERSION);
    
    $this->headLink()->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,700,800');
    
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/css/community/default/print.css?v=' . $VERSION, 'print');
    
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vivin/regula.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vm/yui/viame_form_helper.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vm/vm.js');
    
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/scrollReveal/dist/scrollReveal.min.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/jasny/js/jasny-bootstrap.min.js');
    //$this->headScript()->prependFile('https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/css/community/ninjaplays/js/jquery.mobile.custom/jquery.mobile.custom.min.js');
    $this->headScript()->prependFile('https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.min.js');
    $this->headScript()->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js');
    
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui_combo_local.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui3/build/yui/yui-min.js');
    $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js');
    
    /* MOVED TO GTM
    // Google Analytics
    $this->headScript()->appendScript("
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-1218496-10', 'auto');
        ga('send', 'pageview');
    ");
    */
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->render('../default/includes/header.phtml'); ?>
</head>

<body class="yui-skin-sam yui3-skin-sam">
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5FQJS9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5FQJS9');</script>
<!-- End Google Tag Manager -->

<?php echo $this->placeholder('body'); ?>

<?= $this->inlineScript() ?>

<script type="text/javascript">$(document).bind("mobileinit", function(){$.extend(  $.mobile , {autoInitializePage: false})});</script>

<script type="text/javascript">
//$.mobile.autoInitializePage = false;
//$.mobile.pushStateEnabled = false;
//$.mobile.ignoreContentEnabled = true;	

$(function(){
  // Bind the swipeHandler callback function to the swipe event on div.box
  $( "div.navmenu" ).on( "swipeleft", navswipeleftHandler );
 
  // Callback function references the event target and adds the 'swipe' class to it
  function navswipeleftHandler( event ){
    $('div.navmenu').offcanvas('hide');
  }
});

$(function(){
  // Hide Menu With Each Click
  $( '.navmenu a' ).click(function(e){
  	  if (!($(this).hasClass('dropdown-toggle'))) {
  	      $('.navmenu').offcanvas('hide');
  	      $('.navmenu li').removeClass('active');
  	      $(this).parent('li').addClass('active');
  	      
          if ($(this).attr('href').match(/^\/\#/)) {
      	      //e.preventDefault(); //used to prevent default actions
              $('html,body').animate({
                scrollTop: $( $(this).attr('href').substring(1) + '_section' ).offset().top - 50
                }, 500);
              return false;
      	  }
  	  }
   });
   
   $( 'a.internal_link' ).click(function(e){
      if ($(this).attr('href').match(/^\/\#/)) {
  	      //e.preventDefault(); //used to prevent default actions
          $('html,body').animate({
            scrollTop: $( $(this).attr('href').substring(1) + '_section' ).offset().top - 50
            }, 500);
          return false;
  	  }
   });
});

// Full Width Headers
$(document).ready(function() {
    $('.navmenu a[href="' + window.location.pathname + window.location.hash + '"]').parent('li').addClass('active');
    
    fullPageAdjust();
    
    if (window.location.hash) {
        $('html,body').animate({
          scrollTop: $( window.location.hash + '_section' ).offset().top - 50
          }, 500);
    }
});
function fullPageAdjust() {
    $('.fullPageAdjust .fixedWidth').width($('.fullPageAdjust .fixedWidth').width());
    $('.fullPageAdjust').css('margin-left', '-'+(($(window).width() - $('#doc4').width()) / 2)+'px');
    $('.fullPageAdjust').outerWidth($(window).width());
} 
$(window).resize(function() {
    fullPageAdjust();
});

// Scroll Top
$(window).scroll(function() {
    if ($(this).scrollTop() > $(window).height()) {
        $('div.scroll-top').addClass('on');
    } else {
        $('div.scroll-top').removeClass('on');
        $('div.scroll-top').addClass('off');
    }
});
$( 'div.scroll-top' ).click(function() {
    $('div.scroll-top').removeClass('on');
    $('div.scroll-top').addClass('off');
    $('html,body').animate({
        scrollTop: 0
        }, 500);
});

// Modal Images
$(document).ready(function ($) {

	// delegate calls to data-toggle="lightbox"
	$(document).delegate('*[data-toggle="lightbox"]:not([data-gallery="navigateTo"])', 'click', function(event) {
		event.preventDefault();
		return $(this).ekkoLightbox({
			onShown: function() {
				if (window.console) {
					return console.log('Checking our the events huh?');
				}
			},
			onNavigate: function(direction, itemIndex) {
				if (window.console) {
					return console.log('Navigating '+direction+'. Current item: '+itemIndex);
				}
			}
		});
	});

	//Programatically call
	$('#open-image').click(function (e) {
		e.preventDefault();
		$(this).ekkoLightbox();
	});
	$('#open-youtube').click(function (e) {
		e.preventDefault();
		$(this).ekkoLightbox();
	});

	$(document).delegate('*[data-gallery="navigateTo"]', 'click', function(event) {
		event.preventDefault();
		return $(this).ekkoLightbox({
			onShown: function() {
				var a = this.modal_content.find('.modal-footer a');
				if(a.length > 0) {
					a.click(function(e) {
						e.preventDefault();
						this.navigateTo(2);
					}.bind(this));
				}
			}
		});
	});

});

// scrollReveal
window.sr = new scrollReveal({
    mobile: true
});
</script>

<?php // Bad Bot Honey Pot // ?>
<p style="display: none;"><a href="/zfbp/bbhp/" style="visibility: hidden;">This link should not be clicked.</a></p>

</body>
</html>