<?php
$VERSION = '20150515';

echo $this->docType();
?>

<?php
    #$this->headTitle('ViaMe');
    $this->headTitle()->setSeparator(' : ');

    $this->headMeta()->appendHttpEquiv('content-type', 'text/html; charset=UTF-8');
    $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    $this->headMeta()->appendName('cache-control', 'no-cache');
    $this->headMeta()->appendName('pragma', 'no-cache');
    $this->headMeta()->appendName('expires', 'Wed, 01 Jan 1997 00:00:00 GMT');
    
    #$this->headMeta()->appendName('google-site-verification', 'Kw_IAust9ES4n-_pF8nfkQAvCt2e6Sih1xZ4EiUhlEA');
    #$this->headMeta()->appendName('msvalidate.01', 'A616F9628150988274D546584CA6856E');
    #$this->headMeta()->appendName('y_key', 'a0fd6bbee8c05e61');
    #try {
    #    // Have to catch exceptions thrown when wrong doctype
    #    $this->headMeta()->appendProperty('fb:page_id', '88202206436');
    #} catch (Exception $e) { }
    
    #$this->headLink(array('rel' => 'icon', 'href' => $this->internal->vars->static_host . '/css/community/ninjaplays/assets/favicon.ico'));
    #$this->headLink(array('rel' => 'shortcut icon', 'href' => $this->internal->vars->static_host . '/css/community/ninjaplays/assets/favicon.ico'));
    
    // Reversed Order to keep print.css last if printing
    $this->headLink()->prependStylesheet('https://jasny.github.io/bootstrap/examples/navmenu-push/navmenu-push.css');
    $this->headLink()->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css');
    $this->headLink()->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css');
    $this->headLink()->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css');
    
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/community/ninjaplays/stylesheet.css?v=' . $VERSION);
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/theme/default/stylesheet.css?v=' . $VERSION, 'screen', false, array('title' => 'Default'));
    $this->headLink()->prependStylesheet($this->internal->vars->static_host . '/css/community/default/stylesheet.css?v=' . $VERSION);
    
    
    $this->headLink()->appendStylesheet($this->internal->vars->static_host . '/css/community/default/print.css?v=' . $VERSION, 'print');
    
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vivin/regula.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vm/yui/viame_form_helper.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/vm/vm.js');
    
    $this->headScript()->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js');
    $this->headScript()->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js');
    
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui_combo_local.js');
    $this->headScript()->prependFile($this->internal->vars->static_host . '/js/yui/yui3/build/yui/yui-min.js');
    $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js');
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
    /* For use if pages are to be called in iframes that should explode
    <base target="_top" />
    */
?>
<?= $this->render('../default/includes/header.phtml'); ?>
</head>

<body class="yui-skin-sam yui3-skin-sam">

<!-- Begin Page -->
<div id="page" class="type_<?= $this->internal->target->type ?> id_<?= $this->internal->target->id; ?>">

    <!-- Begin Page Body -->
    <div id="page_body" class="<?php $front = Zend_Controller_Front::getInstance(); echo $front->getRequest()->getModuleName() . '_module ' . $front->getRequest()->getControllerName() . '_controller ' . $front->getRequest()->getActionName() . '_action'; ?>" style="margin: 0;">
    
        <!-- Begin SubLayout -->
        <div class="page_body_internal">					
        	<div id="bd"><div id="yui-main"><div class="yui-b">
        		<div id="content_area" style="margin: 1em;"><?= str_replace('http://', 'https://', $this->layout()->content) ?></div>
        	</div></div></div>
        </div>
        <!-- End SubLayout -->

    </div>
    <!-- End Page Body -->

</div>
<!-- End Page -->

<?= $this->inlineScript() ?>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1218496-10', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>