<?php
$module = 'file';

/*
if (!$this->masked && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_WRITE)) {
?>
<p class="administer"><a href="<?= $this->internal->target->pre ?>/<?= $module ?>/create/p/mid/<?= $this->widget->counter ?>/">Upload New File</a></p>
<?php
}
*/

if (isset($this->objects) && $this->objects) {
    $counter = 0;
    
    foreach ($this->objects as $object) {
        $counter++;
        if ($this->internal->target->acl->owner ||
            $object->allowed === null ||
            $object->show_on_fail ||
            ($object->allowed && ($object->privilege >= ViaMe_Controller_Action::ACL_READ)) ||
            ($this->internal->target->acl->recursive && ($this->internal->target->acl->privilege >= ViaMe_Controller_Action::ACL_READ))) {
            
            // Create the link
            /*
            $link = 'http://' . $this->internal->vars->host . '/' . $this->SEO_Urlify($object->title) . '/s';
            if ($this->masked) {
                $link .= $this->internal->target->pre . "/$module/view/p/mid/" . $this->masked . '/id/' . $object->counter . '/';
            }
            else {
                if ($object->com_id && ((isset($this->internal->params->com_id) && $this->internal->params->com_id) || $object->com_id != $this->internal->community->id)) { $link .= '/com/' . $object->com_id; }
                elseif ($object->net_id) { $link .= '/net/' . $object->net_id; }
                elseif ($object->via_id) { $link .= '/via/' . $object->via_id; }
                
                $link .= "/$module/view/p/mid/" . $object->matrix_counter . '/id/' . $object->counter . '/';
            }
            */
            $link = $this->ContentLink(array('object' => $object, 'view' => $this));
            
            // Access link - Sync with View Controller
            $access_link = (
                $object->public_location ? 
                    ($this->internal->config->upload->public_server . ($object->title ? '/' . $this->escape($this->SEO_Urlify($object->title)) : '/No-Title') . '/' . $object->file_dir . '/' . $object->file_id . '/' . urlencode($object->file_name))
                    :
                    (($object->title ? '/' . $this->escape($this->SEO_Urlify($object->title)) . '/s' : '') . $this->internal->target->pre . '/file/view/check/mid/' . ((isset($this->masked) && $this->masked) ? $this->masked : $object->matrix_counter) . '/id/' . $object->counter . '/file/' . $object->file_id . '/' . urlencode($object->file_name))
            );
?>

<div class="<?= $module ?> <?= ($counter % 2) ? 'odd' : 'even' ?><?= (isset($this->widget->widget_hide_summary) && $this->widget->widget_hide_summary) ? ' hide_summary' : '' ?><?= ($counter == 1) ? ' firstitem' : (($counter == count($this->objects)) ? ' lastitem' : '') ?><?= ($object->active == false ? ' draftitem' : '') ?><?= ($object->published_display_activated == false ? ' futureitem' : '') ?><?= ($object->published_display_expired == true ? ' expireditem' : '') ?>">
    <div class="title"><a href="<?= $link ?>"><?= $this->escape($object->title) ?></a><?= ($object->active == false ? ' <span class="drafttype">(Draft)</span>' : '') ?><?= ($object->published_display_activated == false ? ' <span class="futuretype">(Future)</span>' : '') ?><?= ($object->published_display_expired == true ? ' <span class="expiredtype">(Expired)</span>' : '') ?></div>
    <div class="author">Uploaded By <?= $this->ProfileDisplay(array('profile' => $object, 'internal' => $this->internal)) ?></div>
    <div class="datetime">
<?php
                $date = new Zend_Date();
                $date->set($object->published_display_date, Zend_Date::ISO_8601);
                if (isset($this->internal->member)) {
                    $date->setTimezone($this->internal->member->timezone);
                    echo $date->toString(Zend_Date::DATE_MEDIUM) . ' <span class="time">' . $date->toString(Zend_Date::TIME_SHORT) . '</span>';
                }
                else {
                    $date->setTimezone($this->internal->config->timezone);
                    echo $date->toString(Zend_Date::DATE_MEDIUM) . ' <span class="time">' . $date->toString(Zend_Date::TIME_SHORT . ' z') . '</span>';
                }
?>
    </div>

<?php if (!(isset($this->widget->widget_hide_summary) && $this->widget->widget_hide_summary)) { ?>
    
    <div class="summary">
        <table class="fileinfo">
            <tr>
                <td rowspan="3" width="40">
                    <a href="<?= ($access_link ? $access_link : $link) ?>"><img src="http://www.stdicon.com/crystal/<?= ($object->file_name ? $object->file_name : $object->file_type) ?>?size=40&default=http%3A%2F%2Fwww.stdicon.com%2Fcrystal%2Fapplication%2Foctet-stream%3Fsize%3D40" /></a>
                </td>
                <td class="item">FileName:</td>
                <td class="value"><a href="<?= ($access_link ? $access_link : $link) ?>"><?= $object->file_name ?></a></td>
            </tr>
            <tr>
                <td class="item">FileSize:</td>
                <td class="value">
<?php

$size = $object->file_size;
$ext = 'Byte';

if ($size >= (1024 * 1024 * 1024)) {
    $size = $size / 1024 / 1024 / 1024;
    $ext = 'GB';
}
elseif ($size >= (1024 * 1024)) {
    $size = $size / 1024 / 1024;
    $ext = 'MB';
}
elseif ($size >= 1024) {
    $size = $size / 1024;
    $ext = 'KB';
}

echo Zend_Locale_Format::toNumber($size, array('precision' => 2)) . " $ext" . ($size > 1 ? 's' : '');
?>
                </td>
            </tr>
            <tr>
                <td class="item">MimeType:</td>
                <td class="value"><?= $object->file_type ?></td>
            </tr>
        </table>
        
        <?php # ($object->summary ? $this->escape($object->summary) : $this->SEO_Quip($object->content, 256)) ?>
    </div>
    
<?php if ($this->widget->interactive && ($this->masked ? $object->x_interactive : true)) { ?>
    <div class="interact">
         <div class="comments"><span class="begin_comment_count">&nbsp;</span><a href="<?=$link?>#comments_list" class="comment_count"><?= $object->total_comments_count ?></a><span class="end_comment_count">&nbsp;</span> <a href="<?=$link?>#comments_list">Comment(s)</a></div>
        <div class="rating">Rating <span class="count rc<?= floor($object->rating * 2) ?>"><?= ($object->rating ? $object->rating : 'N/A') ?></span></div>
    </div>
<?php } ?>

<?php } ?>

</div>

<?php
        }
    }
}
?>
