<p>Please feel free to peruse the Community and even start participating! Aside from all of the information you now have at your fingertips, you can start sharing your own thoughts and information with thousands of other <strong><?= $this->internal->community->display ?> Members</strong>! At the top of our <a href="http://<?= $this->internal->vars->host ?>">homepage</a> (<a href="http://<?= $this->internal->vars->host ?>"><?= $this->internal->vars->host ?></a>), you will find your tool bar. This is your guide to your space and your very own publishing tools.</p>

<p>Once logged in, you can write blogs, articles, start your own message boards, create your own research reports, and upload research media to share with the rest of the <strong><?= $this->internal->community->display ?> Community</strong>.</p>

<p>Please feel free to ask us any questions. We always do our best to get back to you ASAP with an answer. Also, we love feedback, site critique and suggestions, so send them in. We take your comments and suggestions very seriously, so please don't be shy.</p>

<p>Thanks again for becoming a <strong><?= $this->internal->community->display ?> Member</strong>. We look forward to having you as part of our rapidly growing Community.</p>

<p>Sincerely,</p>

<p><strong><?= $this->internal->community->display ?></strong></p>