<p>We are processing your change email request.  To complete the process of changing your <?= $this->internal->community->display ?> login email address, please review the information and click on the verification link below.</p>

<p><strong>Old Email Address:</strong> <?=$this->old_email?></p>

<p><strong>New Email Address:</strong> <?=$this->new_email?></p>

<?php /* Confirmation Key : <?=$this->key?> */ ?>

<p>To confirm this change, <a href="<?= 'https://' . $this->internal->vars->host . '/member/update/email/vmpd_bpip/1/new_email/' . $this->escape($this->new_email) . '/key/' . $this->key . '/'; ?>">click here</a>.</p>

<p>If you did not initiate this request, do nothing, and the email address on file will not be changed.</p>