<!-- Begin Module -->
<div class="cm decorated">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Reset Password</td>
                    <td class="sep"></td>
                    <td class="mn2">Reset your login password</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd padded">

<p>Please enter the email address you registered with.  Instructions on how to reset your password will be sent there.</p>

<?= $this->render('form.phtml') ?>

    </div>
    <div class="ft">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div></div>
    </div>
    
    <span class="icon"></span>
</div>
<!-- End Module -->