<!-- Begin Module -->
<div class="cm decorated plain successmessage">
    <div class="hd">
        <div class="dec"><div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
        <div class="con">
        	<table class="table">
                <tr>
                    <td class="lt"></td>
                    <td class="mn1">Setup Alerts</td>
                    <td class="sep"></td>
                    <td class="mn2">Receive Alerts Via Text Message</td>
                    <td class="rt"></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="bd">
        <p class="success">Your email address has been confirmed and your account is activated.  Enter your mobile number for timely alerts.</p>
        <p><strong>You're almost finished!</strong>  Avoid delays now by receiving our mobile text alerts, which are far quicker and more timely than email.  <strong>Individuals who provide their mobile phone numbers will be the first to receive our alerts.</strong></p>
        <p><strong>Please provide your mobile phone number below.</strong> Make sure to include your country code, area code and phone number. Once you have finished, hit the <strong>"Sign-Up For Mobile Alerts"</strong> button and a confirmation code will be sent via text directly to your mobile phone. Simply enter the confirmation code on the next page and you will be all dialed in to start receiving the <strong>Ninja Plays Mobile Text and Email Alerts</strong>.</p>


<div style="width:400px; margin: 0 auto;">
<form id="alert_form" name="alert_form" enctype="application/x-www-form-urlencoded" method="POST" action="/profile/alert/add/" class="form" onSubmit="return (YAHOO.viame.vivin_regula.validate(this, { groups: [regula.Group.alert_form] }) && YAHOO.viame.dubsub.check(this));">
<input type="hidden" name="type" value="2" id="type" />
<input type="hidden" name="vmpd_bpip" value="1" id="vmpd_bpip" />
<input type="hidden" name="vmpd_npr" value="1" id="vmpd_npr" />
<input type="hidden" name="vmpd_nar" value="1" id="vmpd_nar" />
<input type="hidden" name="vmpd_nsslr" value="1" id="vmpd_nsslr" />
<input type="hidden" name="redirect" value="<?= urlencode(isset($this->internal->params->redirect) && $this->internal->params->redirect ? $this->internal->params->redirect : '/') ?>" id="redirect" />
  <dl class="zend_form">
    <dt id="main-label">&#160;</dt>
    <dd id="main-element">
      <fieldset id="fieldset-main">
        <dl>
          <dt id="identifier-label">
            <label for="identifier" class="required">Mobile # : <span class="netdown">US Numbers Should Start With "1"</span></label>
          </dt>
          <dd id="identifier-element">
            <input type="text" name="identifier" id="identifier" value="" maxlength="256" class="regula-validation" data-constraints="@Required(label=&quot;mobile #&quot;, message=&quot;The {label} field cannot be empty.&quot;, groups=[alert_form])" />
            <p class="description">Enter your phone number, <strong class="netdown">including full country code and area code</strong> for instant text alerts (i.e., 16195551212 for U.S. domestic users; International users should not include 011 or 00)</p>
          </dd>
        </dl>
      </fieldset>
    </dd>
    <dt id="buttons-label">&#160;</dt>
    <dd id="buttons-element">
      <fieldset id="fieldset-buttons">
        <dl>
          <dt id="submit-label">&#160;</dt>
          <dd id="submit-element">
            <input type="button" value="No Thanks" onclick="location='<?= urlencode(isset($this->internal->params->redirect) && $this->internal->params->redirect ? $this->internal->params->redirect : '/') ?>';" />
            <input type="submit" name="submit" id="submit" value="Sign-Up For Mobile Alerts" />
          </dd>
        </dl>
      </fieldset>
    </dd>
  </dl>
</form>
</div>


    </div>
    <div class="ft">
        <div class="dec">
            <div class="lt"></div><div class="mn"></div><div class="rt"></div>
        </div>
    </div>
    <span class="icon"></span>
</div>
<!-- End Module -->