This is a custom build of Shadowbox version 3.0rc1 that contains only a
subset of the features available. It was compiled using the build tool at
<http://shadowbox-js.com/download.html>. This particular build includes support
for the following:

adapter:  yui
language: en
players:  flv, html, iframe, img, qt, swf, wmp

Support for CSS selectors is also included via Sizzle.js <http://sizzlejs.com/>.
