<?php echo $this->render('access/subscribesuccess.phtml'); ?>

<?php $this->headScript()->captureStart(); ?>

window.dataLayer = window.dataLayer || [];
dataLayer.push({
    'adwordsConversion_id': '<?= (isset($this->internal->cookie->gawci) && $this->internal->cookie->gawci ? $this->internal->cookie->gawci : '1071423029') ?>',
    'adwordsConversion_label': '<?= (isset($this->internal->cookie->gawcl) && $this->internal->cookie->gawcl ? $this->internal->cookie->gawcl : 'vibBCIv2rwQQtbzy_gM') ?>',
    'adwordsConversion_value': '<?= (isset($this->conversion_value) && $this->conversion_value ? $this->conversion_value : 0) ?>',
    
    'ecommerce': {
        'purchase': {
            'actionField': {
                'id': '<?= isset($this->initial_invoice_number) ? $this->initial_invoice_number : 'Default' ?>',
                'affiliation': '<?= isset($this->internal->community->display) && $this->internal->community->display ? $this->internal->community->display : $this->internal->community->name ?>',
                'revenue': '<?= (isset($this->conversion_value) && $this->conversion_value ? $this->conversion_value : 0) ?>',
                'tax': '0',
                'shipping': '0'
                <?php if (isset($this->promo) && isset($this->promo->code) && $this->promo->code) { ?>
                , 'coupon': '<?= $this->promo->code ?>'
                <?php } ?>
            },
            'products': [
                {
                    'name': '<?= (isset($this->access_selected->display) && $this->access_selected->display ? $this->access_selected->display : $this->access_selected->title) ?>',
                    'id': '<?= $this->internal->params->access_selection ?>',
                    'price': '<?= (isset($this->conversion_value) && $this->conversion_value ? $this->conversion_value : 0) ?>',
                    'quantity': 1
                }
            ]
        }
    }
});

<?php $this->headScript()->captureEnd(); ?>




<?php /* MOVED TO GTM

<!-- Begin Google Analytics Ecommerce Tracking -->
<script type="text/javascript">
ga('require', 'ecommerce');
ga('ecommerce:addTransaction', {
  'id': '<?= $this->initial_invoice_number ?>',                  // Transaction ID. Required.
  'affiliation': '<?= $this->internal->community->display ?>',   // Affiliation or store name.
  'revenue': '<?= $this->conversion_value ?>',                   // Grand Total.
  'shipping': '0',                                               // Shipping.
  'tax': '0'                                                     // Tax.
});
ga('ecommerce:addItem', {
  'id': '<?= $this->initial_invoice_number ?>',                  // Transaction ID. Required.
  'name': '<?= (isset($this->access_selected->display) && $this->access_selected->display ? $this->access_selected->display : $this->access_selected->title) ?>', // Product name. Required.
  'sku': '<?= $this->internal->params->access_selection ?>',                                              // SKU/code.
  'price': '<?= $this->conversion_value ?>',                     // Unit price.
  'quantity': '1'                                                // Quantity.
});
ga('ecommerce:send');
</script>
<!-- End Google Analytics Ecommerce Tracking -->


<!-- Begin Google Code for SCN EO Conversion Page -->
<script type="text/javascript">
var google_conversion_id = 1071423029;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "vibBCIv2rwQQtbzy_gM";
var google_conversion_value = <?= (isset($this->conversion_value) && $this->conversion_value ? $this->conversion_value : 0) ?>;
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1071423029/?value=<?= (isset($this->conversion_value) && $this->conversion_value ? $this->conversion_value : 0) ?>&amp;label=vibBCIv2rwQQtbzy_gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- End Google Code for SCN EO Conversion Page -->

*/ ?>