<div id="menubar" class="nonmember yuimenubar yuimenubarnav">
    <div class="bd">

        <ul class="first-of-type last-of-type">
            <li class="yuimenubaritem logo first-of-type"><a class="yuimenubaritemlabel" href="/"><span class="icon"></span><?= $this->internal->community->display ?></a></li>
            
            <li class="yuimenubaritem home" style="padding-right: 150px;"><span style="font-size: 11px; font-weight: normal; line-height: 12px;"><a href="/?vmpd_ckstr[signup_entrance]=Header_Banner_SCNEO&vmpd_ckstr[click_track]=Header_Banner_SCNEO&vmpd_ckstr_redirect=/pages/SCNEO/v1/"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/scneo/scneo_header_banner.png" /></a><br /><a href="/via/21066/?vmpd_paid=1&vmpd_ckstr[signup_entrance]=Header_Banner_SCNEO&vmpd_ckstr[click_track]=Header_Banner_SCNEO">Existing Members, Click Here to Login!</a><!-- Sign up for a FREE account today. --></span></li>
            
            <li class="yuimenubaritem register last-of-type">
                <a class="yuimenubaritemlabel" href="/Register/s/member/register/p/shortform/1/signup_entrance/TB-Register-Button/" rel="nofollow"><span class="icon"></span>Join the Conversation</a>
            </li>
        </ul>
                 
    </div>
</div>

<div id="menubar2" class="member yuimenubar yuimenubarnav"></div>
