<?php $NoXTest = false;  if (rand(0,1)) { $NoXTest = true; } $NoXTest = false; ?>

<style type="text/css">
<!--
#modal_contents h1 {
	font-family:'Oxygen',sans-serif;
	font-weight:normal;
	font-size:28px;
	color:#FFF;
	margin:0 auto;
	line-height:40px;
	text-align:center;
}
#modal_contents input {
	border: none;
	border-radius: 3px;
	font-family: "Oxygen", sans-serif;
	font-size: 22px;
	font-weight: 400;
	height: 50px;
	width: auto;
	line-height: 50px;
	padding: 5px 5px 5px 10px;
}

@font-face {
  font-family: 'Oxygen';
  font-style: normal;
  font-weight: 300;
  src: local('Oxygen Light'), local('Oxygen-Light'), url(https://fonts.gstatic.com/s/oxygen/v5/AwBqWF2kjhlybWamaKMPcVtXRa8TVwTICgirnJhmVJw.woff2) format('woff2'), url(https://fonts.gstatic.com/s/oxygen/v5/AwBqWF2kjhlybWamaKMPcT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
}
@font-face {
  font-family: 'Oxygen';
  font-style: normal;
  font-weight: 400;
  src: local('Oxygen'), local('Oxygen-Regular'), url(https://fonts.gstatic.com/s/oxygen/v5/78wGxsHfFBzG7bRkpfRnCQ.woff2) format('woff2'), url(https://fonts.gstatic.com/s/oxygen/v5/RzoNiRR1p2Mqyyz2RwqSMw.woff) format('woff');
}
@font-face {
  font-family: 'Oxygen';
  font-style: normal;
  font-weight: 700;
  src: local('Oxygen Bold'), local('Oxygen-Bold'), url(https://fonts.gstatic.com/s/oxygen/v5/yVHpdQrmTj9Kax1tmFSx2ltXRa8TVwTICgirnJhmVJw.woff2) format('woff2'), url(https://fonts.gstatic.com/s/oxygen/v5/yVHpdQrmTj9Kax1tmFSx2j8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
}
-->
</style>

<div id="signup_popup" style="display: none; border: none; text-align: left;">
    <div class="bd" style="padding: 1.9em; border: 3px solid #fff; background: url(<?= $this->internal->vars->static_host ?>/pages/SCNEOL/v1/images/background.jpg) center center no-repeat; background-size: cover; border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px;">
        <a href="javascript:void(null);" rel="nofollow" onclick="YAHOO.viame.modal.signup_popup_handleCancel();" style="color: #f00; display: block; position: absolute; top: -25px; right: -25px;<?= ($NoXTest ? ' visibility: hidden;' : '') ?>"><img src="<?= $this->internal->vars->static_host ?>/pages/SCNEO/v1/inc/img/btn_close.png" alt="Close" /></a>
        <div id="modal_contents">
        	<p><img src="<?= $this->internal->vars->static_host ?>/pages/SCNEOL/v1/images/logo.png" /></p>
            <h1><strong>Free Premium Stock Picks</strong> via email and mobile text alerts. <strong>It's 100% FREE.</strong> No strings attached, <strong>no credit card required</strong> and <strong>absolutely no obligation</strong> to anything whatsoever. Sign-up now!</h1>
            <p style="text-align: center;" align="center"><img src="<?= $this->internal->vars->static_host ?>/pages/SCNEOL/v1/images/arrow-down.png" /></p>
            
            <form id="scneol_form" name="scneol_form" enctype="application/x-www-form-urlencoded" class="form regula-validation" method="post" action="/member/scneol/">
                <input type="hidden" name="signup_entrance" value="SCNEOL-NU-Modal-Get-2S<?= ($NoXTest ? '-NoX' : '') ?>" />
                <input type="hidden" name="click_track" value="SCNEOL-NU-Modal-Get-2S<?= ($NoXTest ? '-NoX' : '') ?>" />
                <table border="0" cellpadding="0" cellspacing="5" align="center" style="margin: 0 auto;">
                
                    <tr>
                        <td width="50%"><input type="text" autocomplete="off" placeholder="First Name" name="first_name" id="first_name" value="" maxlength="32" /></td>
                        <td width="50%"><input type="text" autocomplete="off" placeholder="Last Name" name="last_name" id="last_name" value="" maxlength="32" /></td>
                    </tr>
                    <tr>
                    	<td align="left" colspan="2" style="padding-top: 3px;"><input type="text" autocomplete="off" placeholder="Email Address" name="email" id="email" value="" maxlength="256" class="regula-validation" data-constraints="@Email(label=&quot;email address&quot;, message=&quot;The {label} was not formatted properly.&quot;, groups=[scneol_form])" style="width: 350px;" /> <input type="button" value="SIGN UP" style="height: 61px; padding: 5px; color: #fff; background-color: #3599e0; background-image: none;" onclick="YAHOO.viame.modal.signup_popup_handleSubmit();">/></td>
                    </tr>
                
                </table>
            </form>
            
        </div>
    </div>
</div>

<div id="signup_popup_success" style="display: none; border: none; text-align: left;">
    <div class="bd" style="padding: 0; border: 3px solid #000; background-color: #fff; border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px;">
        <a href="javascript:void(null);" rel="nofollow" onclick="YAHOO.viame.modal.signup_popup_success_handleCancel();" style="color: #f00; display: block; position: absolute; top: 10px; right: 10px;"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/close.png" alt="Close" /></a>
        <div style="padding: 1em; margin-bottom: 1em; background: #f0efef url(<?= $this->internal->vars->static_host ?>/css/theme/default/assets/stockhq/header_bg.png) center center repeat-x; border-top-left-radius: 10px; -moz-border-radius-topleft: 10px; -webkit-border-topleft-radius: 10px; border-top-right-radius: 10px; -moz-border-radius-topright: 10px; -webkit-border-topright-radius: 10px;"><span style="color: #193764; font-size: 30px;">Check Your Email</span></div>
        <div style="padding: 0 1em 1em 1em; font-size: 120%; line-height: 140%;">
            <div><strong>To complete the sign-up process, <span style="color: #193764;">you must verify your email address</span>. Don't worry, it's quick and easy!</strong></div>
            <div style="margin: 12px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Go to your inbox now.</div>
            <div style="margin: 5px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Find the verification email from SmallCap Network (<strong>you might need to check your spam folder</strong>).</div>
            <div style="margin: 5px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;"><strong>Click on the verification link</strong> provided in the email.</div>
            <div style="margin: 5px 0 12px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Follow the instructions to activate your <strong>mobile text alerts</strong>.</div>
            
            <div style="font-size: 14px; line-height: 120%; margin-bottom: 1em;">Once you finish setting up your mobile alerts, you will automatically be added to our priority list of Members who receive our picks before anyone else.</div>

            <div style="font-size: 14px; line-height: 120%;">Also, <strong>make sure to add our email address to your contact list</strong> to ensure delivery of our Newsletter straight to your inbox.</div>
        </div>
    </div>
</div>



<?php $this->inlineScript()->captureStart() ?>
YAHOO.util.Event.onDOMReady(function () {
	YAHOO.namespace("viame.modal");
	
	var pagesToSkip = 0;
	var timesToDisplay = 1;
	var displayDelay = 2000;
	
	YAHOO.viame.modal.loadupModalSignup = (function() {
	    // Define various event handlers for Dialog
		YAHOO.viame.modal.signup_popup_handleSubmit = (function() {
		    if ( YAHOO.viame.vivin_regula.validate(YAHOO.util.Dom.get('scneol_form'), { groups: [regula.Group.scneol_form] }) ) {
		        
		        // Check Email Before Submitting
		        validEmail = true;
			    
                $.ajax({
                    url: "/member/ajax/checkemail_verify/",
                    cache: false,
                    async: false,
                    data: { no_cache: 1, email:  $('#email').val() },
                    success: function(data) {
                        if (data == 'false') {
                            YAHOO.viame.modal.emailErrorDialog = new YAHOO.widget.SimpleDialog("emailerrorsimpledialog", {
                                width: "300px",
                                fixedcenter: true,
                                visible: true,
                                draggable: false,
                                close: true,
                                modal: true,
                                text: '<p style="text-align: left;">That email address appears to be invalid. Please try again or select a different email address.</p>',
                                icon: YAHOO.widget.SimpleDialog.ICON_WARN,
                                constraintoviewport: true,
                                buttons: [ { text: "OK", handler: function() { setTimeout(function() { $('#email').select(); }, 100); this.destroy(); }, isDefault:true } ]
                            } );
                        	YAHOO.viame.modal.emailErrorDialog.setHeader("Invalid Email Address");
                        	YAHOO.viame.modal.emailErrorDialog.render(document.body);
                            
                            //$('#email').val('')
                            
                            validEmail = false;
                        }
                    }
                });
                
		        if ( validEmail && YAHOO.viame.dubsub.check(YAHOO.util.Dom.get('scneol_form')) ) {
        			YAHOO.viame.modal.signup_popup.hide();
        	        YAHOO.viame.modal.signup_popup.submit();
        	        
        	        YAHOO.util.Cookie.set("modal_signed_up", 1, { path: "/" });
        	        
        	        YAHOO.viame.modal.signup_popup_success_handleCancel = (function() {
        	            YAHOO.viame.modal.signup_popup_success.cancel();
        	            slideFixedOut();
        	        });
        	        
        	        YAHOO.util.Dom.setStyle('signup_popup_success', 'display', 'block');
        	        YAHOO.viame.modal.signup_popup_success = new YAHOO.widget.Dialog("signup_popup_success", {
            			width : "40em",
            			fixedcenter : true,
            			draggable: false, 
                        zindex: 10,
                        modal: true,
            			close: false,
            			underlay: 'none',
            			visible : false,
            			constraintoviewport : true,
            			effect: { effect: YAHOO.widget.ContainerEffect.FADE, duration: 0.5 }
            		} );
            		YAHOO.viame.modal.signup_popup_success.render();
        	        YAHOO.viame.modal.signup_popup_success.show();
        	    }
    	    }
		});
		
		YAHOO.viame.modal.signup_popup_handleCancel = (function() {
		    YAHOO.viame.modal.signup_popup.cancel();
		    
		    //YAHOO.viame.modal.signup_popup.hide();
            setTimeout("YAHOO.viame.modal.signup_popup.destroy()", 3000);
		});
		
		YAHOO.viame.modal.signup_popup_handleSuccess = (function(o) { });
		YAHOO.viame.modal.signup_popup_handleFailure = (function(o) { });
		
		YAHOO.util.Dom.setStyle('signup_popup', 'display', 'block');
	
		// Instantiate the Dialog
		YAHOO.viame.modal.signup_popup = new YAHOO.widget.Dialog("signup_popup", {
			width : "66em",
			fixedcenter : true,
			draggable: false, 
            zindex: 10,
            modal: true,
			close: false,
			underlay: 'none',
			visible : false,
			constraintoviewport : true,
			effect: { effect: YAHOO.widget.ContainerEffect.FADE, duration: 0.5 }
		} );
    	
		// Wire up the success and failure handlers
		YAHOO.viame.modal.signup_popup.callback = { success: YAHOO.viame.modal.signup_popup_handleSuccess, failure: YAHOO.viame.modal.signup_popup_handleFailure };
		
		// Render the Dialog
		YAHOO.viame.modal.signup_popup.render();
		YAHOO.viame.modal.signup_popup.show();
	});
	
	YAHOO.viame.modal.ua = navigator && navigator.userAgent;
    YAHOO.viame.modal.href = window && window.location && window.location.href;
    
    YAHOO.util.Cookie.set("cookies_enabled", 1, { path: "/" });
    if (
        YAHOO.util.Cookie.get("cookies_enabled") &&
	    (!YAHOO.env.ua.mobile) &&
        (!(/(Googlebot|Mediapartners-Google|Google Web Preview|Thunderbird)/).test(YAHOO.viame.modal.ua)) &&
        (!(/\/system\/interstitial\//).test(YAHOO.viame.modal.href)) &&
        (typeof(processing_interstitial)==="undefined" || !processing_interstitial) &&
	    (!YAHOO.util.Cookie.get("modal_signed_up")) && 
	    (!pagesToSkip || parseInt(YAHOO.util.Cookie.get("modal_signup")) >= pagesToSkip) &&
	    (!timesToDisplay || !YAHOO.util.Cookie.get("modal_signup") || (parseInt(YAHOO.util.Cookie.get("modal_signup")) < (pagesToSkip + timesToDisplay)))
	   ) {    
    	setTimeout("YAHOO.viame.modal.loadupModalSignup()", displayDelay);
    }
    YAHOO.util.Cookie.set("modal_signup", ((YAHOO.util.Cookie.get("modal_signup") ? parseInt(YAHOO.util.Cookie.get("modal_signup")) : 0) + 1), { path: "/" });
});
<?php $this->inlineScript()->captureEnd() ?>
