<?php $NoXTest = false;  if (rand(0,1)) { $NoXTest = true; } ?>

<div id="signup_popup" style="display: none; border: none; text-align: left;">
    <div class="bd" style="padding: 1.9em; border: 3px solid #000; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/background.png) top center no-repeat; border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px;">
        <a href="javascript:void(null);" rel="nofollow" onclick="YAHOO.viame.modal.signup_popup_handleCancel();" style="color: #f00; display: block; position: absolute; top: 10px; right: 10px;<?= ($NoXTest ? ' visibility: hidden;' : '') ?>"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/close.png" alt="Close" /></a>
        <table width="100%"><tr>
        	<td width="50%" valign="top" style="padding-right: 2em; font-weight: bold;">
                
                <?php /*
            	<div style="color: #193764; font-size: 25px;">Attention Small Cap Investors!</div>
                
                <div style="font-size: 21px; line-height: 24px; padding-bottom: 16px; margin-bottom: 16px; border-bottom: 1px dotted #a5afbe;">Find Out What Traders In the Know Are Saying About 
                <?php
                    if (isset($this->placeholder('related_quotes')->symbols)) {
                        $symbols = $this->placeholder('related_quotes')->symbols;
                        if (count($symbols) < 3) {
                            echo implode(' and ', $symbols);
                        }
                        else {
                            $holder = array_pop($symbols);
                            echo implode(', ', $symbols) . ', and ' . $holder;
                        }
                    }
                    else {
                        echo " Stocks You Own";
                    }
                ?>
                </div>
                
                <div style="color: #193764; font-size: 18px;">GET FREE ACCESS TO:</div>
                
                <div style="margin: 7px 0; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Small Cap Stocks Before They Breakout!</div>
                <div style="margin: 7px 0; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Small Cap Stock Traders Who Consistently Kill It For Huge Gains!</div>
                <div style="margin: 7px 0; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat; padding-bottom: 16px; margin-bottom: 16px; border-bottom: 1px dotted #a5afbe;">SCN's Hot Trading Alert Newsletter and Much More!</div>
                
                <div style="color: #193764; font-size: 20px;">It's ALL FREE to<br />SmallCap Network Members</div>
                */ ?>
                
                <div style="color: #193764; font-size: 25px;">Attention, Small Cap Investors!</div>
                
                <div style="margin-top: .5em; margin-bottom: 1em; border-bottom: 1px dotted #a5afbe;">
                    <p style="font-size: 16px; margin-bottom: 16px;">If you invest or trade small cap stocks or penny stocks, our site and daily newsletter is an absolute must.</p>
                    <ul>
                        <li>Uncover the hidden value of select small cap stocks</li>
                        <li>Discover the secrets to playing penny stocks</li>
                        <li>Interact with a community of like-minded investors</li>
                    </ul>
                </div>

                <div style="color: #193764; font-size: 16px;">Here's Just a Few of Our Most Recent Winners!</div>
                
                <div align="center" style="margin: 6px 0 13px 0; padding-bottom: 6px; border-bottom: 1px dotted #a5afbe; font-size: 18px;">
                <table align="center">
                    <tr>
                        <td align="center" valign="middle" style="padding: 3px 10px;">DDD<br /><span class="uptick">+64%</span></td>
                        <td align="center" valign="middle" style="padding: 3px 10px;">RAD<br /><span class="uptick">+240%</span></td>
                        <td align="center" valign="middle" style="padding: 3px 10px;">LEDS<br /><span class="uptick">+85%</span></td>
                        <td align="center" valign="middle" style="padding: 3px 10px;">EGHT<br /><span class="uptick">+102%</span></td>
                    </tr>                    
                </table>
                </div>
                
                <div style="color: #193764; font-size: 20px;">Do Yourself a Favor and Become an<br />SCN Member Today. <span class="netdown"><u>It's FREE!</u></span></div>
                
                <div style="margin-top: 1em;">
                    <strong>Login or Sign Up Using:</strong>
                    <ul class="social_login straight" style="margin-left: 2em;">
                        <li class="openid"><a title="OpenID" href="/member/openid/login/">OpenID</a></li>
                        <li class="facebook"><a title="Facebook" href="/member/oauth/login/?provider=facebook-oauth2">Facebook</a></li>
                        <li class="google"><a title="Google" href="/member/oauth/login/?provider=google-oauth2">Google</a></li>
                        <li class="yahoo"><a title="Yahoo" href="/member/openid/login/?provider=yahoo">Yahoo</a></li>
                        <li class="linkedin"><a title="LinkedIn" href="/member/oauth/login/?provider=linkedin-oauth2">LinkedIn</a></li>
                        <li class="twitter"><a title="Twitter" href="/member/oauth/login/?provider=twitter-oauth1">Twitter</a></li>
                    </ul>
                </div>
            </td>
            <td width="50%" valign="top" style="padding-left: 2em;">
                <img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/header.png" alt="Register Now" style="margin-bottom: 1em;" />
                <form id="member_form" enctype="application/x-www-form-urlencoded" class="form regula-validation shortform" method="post" action="/member/register/p/supershortform/noverify/">
                <input type="hidden" name="vmpd_npr" value="1" />
                <input type="hidden" name="vmpd_nsslr" value="1" />
                <input type="hidden" name="signup_entrance" value="FT-NU-Modal-Get-2S<?= ($NoXTest ? '-NoX' : '') ?>" />
                <input type="text" style="display: none;" />
                <table width="100%">
                    <?php /*
                	<tr>
                    	<td style="width: 150px; color: #fff; font-weight: bold;">Desired Username:</td>
                        <td style="padding: 6px 0;">
                        	<input type="text" name="username" id="username" value="" maxlength="98" class="regula-validation" data-constraints="@Required(label=&quot;username&quot;, message=&quot;The {label} field cannot be empty.&quot;, groups=[modal_registration_form])" style="height: 22px; width: 97%; padding: .4em; border: 1px solid #cfcfcf;" />
                        </td>
                    </tr>
                    */ ?>
                    <tr>
                    	<td style="color: #fff; font-weight: bold;">Email Address:</td>
                        <td style="padding: 6px 0;">
                        	<input type="text" name="email" id="email" value="" maxlength="256" class="regula-validation" data-constraints="@Email(label=&quot;email address&quot;, message=&quot;The {label} was not formatted properly.&quot;, groups=[modal_registration_form])" style="height: 22px; width: 97%; padding: .4em; border: 1px solid #cfcfcf;" />
                        </td>
                    </tr>
                    <tr>
                    	<td>&nbsp;</td>
                        <td style="color: #fff; height: 42px;">
                        	<input type="hidden" name="tos" value="1" /><input type="checkbox" name="tos" id="tos" value="1" checked="checked" class="regula-validation" data-constraints="@Required(message=&quot;You must agree to the Terms of Use.&quot;, groups=[modal_registration_form])" />&nbsp;&nbsp;&nbsp;I Agree to the <!-- <a href="/page/view/p/mid/1/title/Terms+of+Use/" rel="nofollow" style="color: #fff;" target="_blank">Terms of Use</a> -->
                        	<a title="Terms of Service" onclick="return YAHOO.viame.shadowbox.shadowto('/page/view/p/mid/1/title/Terms+of+Use/?vmpd_rqsv=no_layout,vmpd_nsslr,vmcd_ncr&amp;no_layout=1&amp;vmpd_nsslr=1&amp;vmcd_ncr=1', {width: '600px', height: '500px', fixedcenter: true, close: true, draggable: false, modal: true, visible: false});" rel="nofollow" style="color: #fff;" target="_blank" href="/page/view/p/mid/1/title/Terms+of+Use/">Terms of Service</a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                        	<a href="javascript:void(null);" rel="nofollow" onclick="YAHOO.viame.modal.signup_popup_handleSubmit();"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/submit_button.png" /></a>
                        </td>
                    </tr>
                </table>
                </form>
                
                <hr size="1" style="margin: 2.5em 0;" />
                
                <img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/header2.png" alt="Login" style="margin-bottom: 1em;" />
                <p style="color: #fff; font-size: 22px;">Already a member? Sign in by clicking the link below...</p>
                <p align="center" style="margin-bottom: 0;"><a onclick="YAHOO.viame.modal.signup_popup_handleCancel(); return YAHOO.viame.shadowbox.shadowto('/member/login/p/no_layout/1/simple_content/1/signup_entrance/FT-NU-Modal-Get-2S-Login<?= ($NoXTest ? '-NoX' : '') ?>/', { width: '360px', fixedcenter: true, close: true, draggable: false, modal: true, visible: false });" rel="nofollow" href="/member/login/p/signup_entrance/FT-NU-Modal-Get-2S-Login<?= ($NoXTest ? '-NoX' : '') ?>/"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/submit_button2.png" /></a></p>
            </td>
        </tr></table>
    </div>
</div>

<div id="signup_popup_success" style="display: none; border: none; text-align: left;">
    <div class="bd" style="padding: 0; border: 3px solid #000; background-color: #fff; border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px;">
        <a href="javascript:void(null);" rel="nofollow" onclick="YAHOO.viame.modal.signup_popup_success_handleCancel();" style="color: #f00; display: block; position: absolute; top: 10px; right: 10px;"><img src="<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/close.png" alt="Close" /></a>
        <div style="padding: 1em; margin-bottom: 1em; background: #f0efef url(<?= $this->internal->vars->static_host ?>/css/theme/default/assets/stockhq/header_bg.png) center center repeat-x; border-top-left-radius: 10px; -moz-border-radius-topleft: 10px; -webkit-border-topleft-radius: 10px; border-top-right-radius: 10px; -moz-border-radius-topright: 10px; -webkit-border-topright-radius: 10px;"><span style="color: #193764; font-size: 30px;">Check Your Email</span></div>
        <div style="padding: 0 1em 1em 1em; font-size: 120%; line-height: 140%;">
            <div><strong>To complete your registration, <span style="color: #193764;">you must verify your email address</span>. Don't worry, it's quick and easy!</strong></div>
            <div style="margin: 12px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Go to your inbox now.</div>
            <div style="margin: 5px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Find the verification email from SmallCap Network (<strong>you might need to check your spam folder</strong>).</div>
            <div style="margin: 5px 0 5px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;"><strong>Click on the verification link</strong> provided in the email.</div>
            <div style="margin: 5px 0 12px 15px; font-size: 14px; font-weight: normal; padding-left: 29px; background: url(<?= $this->internal->vars->static_host ?>/css/community/smallcapnetwork/assets/signup_modal/check.png) top left no-repeat;">Start reaping the benefits of your free <strong>SCN Membership</strong>!</div>
            
            <div style="font-size: 14px; line-height: 120%; margin-bottom: 1em;">Once you verify your email address, you will have immediate login access to the SmallCap Network Community and will automatically be added to our priority list of Members who receive our Newsletter before anyone else.</div>

            <div style="font-size: 14px; line-height: 120%;">Also, <strong>make sure to add our email address to your contact list</strong> to ensure delivery of our Newsletter straight to your inbox.</div>
        </div>
    </div>
</div>



<?php $this->inlineScript()->captureStart() ?>
YAHOO.util.Event.onDOMReady(function () {
	YAHOO.namespace("viame.modal");
	
	var pagesToSkip = 0;
	var timesToDisplay = 1;
	var displayDelay = 2000;
	
	YAHOO.viame.modal.loadupModalSignup = (function() {
	    // Define various event handlers for Dialog
		YAHOO.viame.modal.signup_popup_handleSubmit = (function() {
		    if ( YAHOO.viame.vivin_regula.validate(YAHOO.util.Dom.get('member_form'), { groups: [regula.Group.modal_registration_form] }) ) {
		        
		        // Check Email Before Submitting
		        validEmail = true;
			    
                $.ajax({
                    url: "/member/ajax/checkemail/",
                    cache: false,
                    async: false,
                    data: { no_cache: 1, email:  $('#email').val() },
                    success: function(data) {
                        if (data == 'true') {
                            YAHOO.viame.modal.emailErrorDialog = new YAHOO.widget.SimpleDialog("emailerrorsimpledialog", {
                                width: "300px",
                                fixedcenter: true,
                                visible: true,
                                draggable: false,
                                close: true,
                                modal: true,
                                text: '<p style="text-align: left;">That email address is already registered. Please <a href="/member/login/p/signup_entrance/FT-NU-Modal-Get/">sign-in</a> or try a different email address.</p>',
                                icon: YAHOO.widget.SimpleDialog.ICON_WARN,
                                constraintoviewport: true,
                                buttons: [ { text: "OK", handler: function() { setTimeout(function() { $('#email').select(); }, 100); this.destroy(); }, isDefault:true } ]
                            } );
                        	YAHOO.viame.modal.emailErrorDialog.setHeader("Duplicate Email Address");
                        	YAHOO.viame.modal.emailErrorDialog.render(document.body);

                            validEmail = false;
                        }
                    }
                });
                
                if (validEmail) {
                    $.ajax({
                        url: "/member/ajax/checkemail_verify/",
                        cache: false,
                        async: false,
                        data: { no_cache: 1, email:  $('#email').val() },
                        success: function(data) {
                            if (data == 'false') {
                                YAHOO.viame.modal.emailErrorDialog = new YAHOO.widget.SimpleDialog("emailerrorsimpledialog", {
                                    width: "300px",
                                    fixedcenter: true,
                                    visible: true,
                                    draggable: false,
                                    close: true,
                                    modal: true,
                                    text: '<p style="text-align: left;">That email address appears to be invalid. Please try again or select a different email address.</p>',
                                    icon: YAHOO.widget.SimpleDialog.ICON_WARN,
                                    constraintoviewport: true,
                                    buttons: [ { text: "OK", handler: function() { setTimeout(function() { $('#email').select(); }, 100); this.destroy(); }, isDefault:true } ]
                                } );
                            	YAHOO.viame.modal.emailErrorDialog.setHeader("Invalid Email Address");
                            	YAHOO.viame.modal.emailErrorDialog.render(document.body);
                                
                                //$('#email').val('')
                                
                                validEmail = false;
                            }
                        }
                    });
                }
                
		        if ( validEmail && YAHOO.viame.dubsub.check(YAHOO.util.Dom.get('member_form')) ) {
        			YAHOO.viame.modal.signup_popup.hide();
        	        YAHOO.viame.modal.signup_popup.submit();
        	        
        	        YAHOO.util.Cookie.set("modal_signed_up", 1, { path: "/" });
        	        
        	        YAHOO.viame.modal.signup_popup_success_handleCancel = (function() {
        	            YAHOO.viame.modal.signup_popup_success.cancel();
        	            slideFixedOut();
        	        });
        	        
        	        YAHOO.util.Dom.setStyle('signup_popup_success', 'display', 'block');
        	        YAHOO.viame.modal.signup_popup_success = new YAHOO.widget.Dialog("signup_popup_success", {
            			width : "40em",
            			fixedcenter : true,
            			draggable: false, 
                        zindex: 10,
                        modal: true,
            			close: false,
            			underlay: 'none',
            			visible : false,
            			constraintoviewport : true,
            			effect: { effect: YAHOO.widget.ContainerEffect.FADE, duration: 0.5 }
            		} );
            		YAHOO.viame.modal.signup_popup_success.render();
        	        YAHOO.viame.modal.signup_popup_success.show();
        	    }
    	    }
		});
		
		YAHOO.viame.modal.signup_popup_handleCancel = (function() {
		    YAHOO.viame.modal.signup_popup.cancel();
		    
		    //YAHOO.viame.modal.signup_popup.hide();
            setTimeout("YAHOO.viame.modal.signup_popup.destroy()", 3000);
		});
		
		YAHOO.viame.modal.signup_popup_handleSuccess = (function(o) { });
		YAHOO.viame.modal.signup_popup_handleFailure = (function(o) { });
		
		YAHOO.util.Dom.setStyle('signup_popup', 'display', 'block');
	
		// Instantiate the Dialog
		YAHOO.viame.modal.signup_popup = new YAHOO.widget.Dialog("signup_popup", {
			width : "66em",
			fixedcenter : true,
			draggable: false, 
            zindex: 10,
            modal: true,
			close: false,
			underlay: 'none',
			visible : false,
			constraintoviewport : true,
			effect: { effect: YAHOO.widget.ContainerEffect.FADE, duration: 0.5 }
		} );
    	
		// Wire up the success and failure handlers
		YAHOO.viame.modal.signup_popup.callback = { success: YAHOO.viame.modal.signup_popup_handleSuccess, failure: YAHOO.viame.modal.signup_popup_handleFailure };
		
		// Render the Dialog
		YAHOO.viame.modal.signup_popup.render();
		YAHOO.viame.modal.signup_popup.show();
	});
	
	YAHOO.viame.modal.ua = navigator && navigator.userAgent;
    YAHOO.viame.modal.href = window && window.location && window.location.href;
    
    YAHOO.util.Cookie.set("cookies_enabled", 1, { path: "/" });
    if (
        YAHOO.util.Cookie.get("cookies_enabled") &&
	    (!YAHOO.env.ua.mobile) &&
        (!(/(Googlebot|Mediapartners-Google|Google Web Preview|Thunderbird)/).test(YAHOO.viame.modal.ua)) &&
        (!(/\/system\/interstitial\//).test(YAHOO.viame.modal.href)) &&
        (typeof(processing_interstitial)==="undefined" || !processing_interstitial) &&
	    (!YAHOO.util.Cookie.get("modal_signed_up")) && 
	    (!pagesToSkip || parseInt(YAHOO.util.Cookie.get("modal_signup")) >= pagesToSkip) &&
	    (!timesToDisplay || !YAHOO.util.Cookie.get("modal_signup") || (parseInt(YAHOO.util.Cookie.get("modal_signup")) < (pagesToSkip + timesToDisplay)))
	   ) {    
    	setTimeout("YAHOO.viame.modal.loadupModalSignup()", displayDelay);
    }
    YAHOO.util.Cookie.set("modal_signup", ((YAHOO.util.Cookie.get("modal_signup") ? parseInt(YAHOO.util.Cookie.get("modal_signup")) : 0) + 1), { path: "/" });
});
<?php $this->inlineScript()->captureEnd() ?>
